# Load libraries

In [1]:
.libPaths()

assign(".lib.loc", "/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/", envir = environment(.libPaths))
.libPaths()

suppressMessages(library("plyr", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("data.table", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
#suppressMessages(library("crayon", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("withr", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("ggplot2", lib.loc = "/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("farver", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("labeling", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("optparse", lib.loc = "/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("dplyr", lib.loc = "/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("withr", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("backports", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("broom", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("rstudioapi", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
#suppressMessages(library("cli", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("tzdb", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("svglite", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("ggeasy", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("sandwich", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
#suppressMessages(library("digest", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("tidyverse", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("BiocGenerics", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("S4Vectors", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("IRanges", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("GenomeInfoDb", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("GenomicRanges", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("Biobase", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("AnnotationDbi", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("GO.db", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("org.Mm.eg.db", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("TxDb.Hsapiens.UCSC.hg19.knownGene", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("rtracklayer", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("cowplot", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("R.oo", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("splitstackshape", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("ggtranscript", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("ggpubr", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("RColorBrewer", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("scales", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))
suppressMessages(library("biomaRt", lib.loc="/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"))

[1] "/home/manuel.tardaguila/conda_envs/general_purpose/lib/R/library"

[1] "/home/manuel.tardaguila/R/x86_64-pc-linux-gnu-library/4.1/"

# Read in the TPM counts of transcripts

setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/")

list_files<-dir()

list_files_sel<-list_files[grep("_Quant.isoforms.results$", list_files)]

str(list_files_sel)
cat("\n")

sample_vector<-gsub("_Quant.isoforms.results$","",list_files_sel)

str(sample_vector)
cat("\n")

df<-as.data.frame(cbind(list_files_sel,sample_vector))
colnames(df)<-c('file','sample')

df$file<-paste("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/",df$file, sep='')


str(df)
cat("\n")

DEBUG<-0

# Initialize a variable to store the merged count matrix (optional, but good practice)
all_TPM_counts <- NULL 


for(i in 1:dim(df)[1]){

    sample_array_sel<-df$sample[i]

    cat("-------------------------->\t")
    cat(sprintf(as.character(sample_array_sel)))
    cat("\n")

    raw_counts_file<-df$file[i]

    raw_counts_df<-read.table(file=raw_counts_file,sep="\t", header=TRUE, stringsAsFactors = FALSE)
    #colnames(raw_counts_df)[8]<-sample_array_sel


    if(DEBUG == 1){
        
        cat("raw_counts_df_0\n")
        str(raw_counts_df)
        cat("\n")
    }


    indx_sel<-which(colnames(raw_counts_df)%in%c('gene_id','transcript_id','TPM'))


    raw_counts_df_subset<-raw_counts_df[,indx_sel]

    

    if(DEBUG == 1){
        
        cat("raw_counts_df_subset_0\n")
        str(raw_counts_df_subset)
        cat("\n")
    }

    colnames(raw_counts_df_subset)[which(colnames(raw_counts_df_subset) == 'TPM')]<-sample_array_sel

    # 3. Initialize or Merge the count matrix
    if (is.null(all_TPM_counts)) {
        # If this is the first sample, initialize the matrix
        all_TPM_counts <- raw_counts_df_subset
        } else {
            # For subsequent samples, merge the new count column 
            # using 'transcript_id' as the key to align the rows.
            all_TPM_counts <- merge(
                x = all_TPM_counts, 
                y = raw_counts_df_subset, 
                by.x = c('gene_id','transcript_id'), 
                by.y = c('gene_id','transcript_id'),
                all = TRUE # Keeps all Gene IDs, even if a sample has a count of 0 for a gene.
            )
        }#if (is.null(all_TPM_counts)

    if(DEBUG == 1){
        
        cat("all_TPM_counts_0\n")
        str(all_TPM_counts)
        cat("\n")
    }

    
}#i in 1:length(sample_array)

cat("all_TPM_counts_0\n")
str(all_TPM_counts)
cat("\n")

all_TPM_counts$transcript_id<-gsub("\\..+$","",all_TPM_counts$transcript_id)
all_TPM_counts$gene_id<-gsub("\\..+$","",all_TPM_counts$gene_id)

str(all_TPM_counts)
cat("\n")

multiVals <- function(x) paste(x,collapse=";")

all_TPM_counts$gene_name <- mapIds(org.Mm.eg.db, keys=all_TPM_counts$gene_id, keytype="ENSEMBL",column="SYMBOL", multiVals=multiVals)

str(all_TPM_counts)
cat("\n")

setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/")

write.table(all_TPM_counts,file="Transcript_TPM_counts.tsv", sep="\t", quote=F, row.names=F)

# Read the results of DRIMSeq modeling

In [27]:
setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/")

DTU_results<-read.table(file="DRIMSeq_DTU_Full_Results_0.1.tsv", sep="\t", header=T)

cat("DTU_results_0\n")
cat(str(DTU_results))
cat("\n")

DTU_results_0
'data.frame':	7891 obs. of  6 variables:
 $ gene_id   : chr  "ENSMUSG00000000028" "ENSMUSG00000000037" "ENSMUSG00000000085" "ENSMUSG00000000094" ...
 $ lr        : num  6.172 1.724 0.656 NA 6.068 ...
 $ df        : int  2 4 2 1 3 3 1 1 2 3 ...
 $ pvalue    : num  0.0457 0.7864 0.7204 NA 0.1083 ...
 $ adj_pvalue: num  0.395 0.965 0.946 NA 0.558 ...
 $ gene_name : chr  "Cdc45" "Scml2" "Scmh1" "Tbx4" ...

In [28]:
DTU_modelled_proportions<-read.table(file="DRIMSeq_DTU_prop_estimates_0.1.tsv", sep="\t", header=T)

DTU_modelled_proportions$feature_id <- gsub("\\..+$", "", DTU_modelled_proportions$feature_id)


cat("DTU_modelled_proportions_0\n")
cat(str(DTU_modelled_proportions))
cat("\n")

DTU_modelled_proportions_0
'data.frame':	21650 obs. of  33 variables:
 $ gene_id    : chr  "ENSMUSG00000000028" "ENSMUSG00000000028" "ENSMUSG00000000028" "ENSMUSG00000000037" ...
 $ feature_id : chr  "ENSMUST00000000028" "ENSMUST00000096990" "ENSMUST00000115585" "ENSMUST00000019101" ...
 $ LM411_R1_t0: num  0.827 0.048 0.125 0.137 0.487 ...
 $ LM411_R2_t0: num  0.827 0.048 0.125 0.137 0.487 ...
 $ LM411_R3_t0: num  0.827 0.048 0.125 0.137 0.487 ...
 $ LM411_R1_t1: num  0.8668 0.1152 0.018 0.0586 0.549 ...
 $ LM411_R2_t1: num  0.8668 0.1152 0.018 0.0586 0.549 ...
 $ LM411_R3_t1: num  0.8668 0.1152 0.018 0.0586 0.549 ...
 $ LM411_R1_t2: num  0.9032 0.0835 0.0133 0.1294 0.4845 ...
 $ LM411_R2_t2: num  0.9032 0.0835 0.0133 0.1294 0.4845 ...
 $ LM411_R3_t2: num  0.9032 0.0835 0.0133 0.1294 0.4845 ...
 $ LM411_R1_t3: num  0.8932 0.0958 0.011 0.1594 0.3406 ...
 $ LM411_R2_t3: num  0.8932 0.0958 0.011 0.1594 0.3406 ...
 $ LM411_R3_t3: num  0.8932 0.0958 0.011 0.1594 0.3406 ...
 $ LM411_R1_t4: num  0.8681 0.1204 0.0115 0.3122 0.4407 ...
 $ LM411_R2_t4: num  0.8681 0.1204 0.0115 0.3122 0.4407 ...
 $ LM411_R3_t4: num  0.8681 0.1204 0.0115 0.3122 0.4407 ...
 $ LM511_R1_t0: num  0.7287 0.0681 0.2032 0.1567 0.3881 ...
 $ LM511_R2_t0: num  0.7287 0.0681 0.2032 0.1567 0.3881 ...
 $ LM511_R3_t0: num  0.7287 0.0681 0.2032 0.1567 0.3881 ...
 $ LM511_R1_t1: num  0.7988 0.1708 0.0304 0.0676 0.4408 ...
 $ LM511_R2_t1: num  0.7988 0.1708 0.0304 0.0676 0.4408 ...
 $ LM511_R3_t1: num  0.7988 0.1708 0.0304 0.0676 0.4408 ...
 $ LM511_R1_t2: num  0.8504 0.1265 0.0231 0.1482 0.3863 ...
 $ LM511_R2_t2: num  0.8504 0.1265 0.0231 0.1482 0.3863 ...
 $ LM511_R3_t2: num  0.8504 0.1265 0.0231 0.1482 0.3863 ...
 $ LM511_R1_t3: num  0.837 0.144 0.019 0.173 0.257 ...
 $ LM511_R2_t3: num  0.837 0.144 0.019 0.173 0.257 ...
 $ LM511_R3_t3: num  0.837 0.144 0.019 0.173 0.257 ...
 $ LM511_R1_t4: num  0.8016 0.1789 0.0195 0.3553 0.3492 ...
 $ LM511_R2_t4: num  0.8016 0.1789 0.0195 0.3553 0.3492 ...
 $ LM511_R3_t4: num  0.8016 0.1789 0.0195 0.3553 0.3492 ...
 $ gene_name  : chr  "Cdc45" "Cdc45" "Cdc45" "Scml2" ...

# Read in ensembl gtf

In [18]:
ensembl_gtf = readGFF("/scratch/manuel.tardaguila/Santos/Mus_musculus.GRCm39.115.gtf")

In [19]:
str(ensembl_gtf)

'data.frame':	2476976 obs. of  26 variables:
 $ seqid                   : Factor w/ 38 levels "1","2","X","3",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ source                  : Factor w/ 8 levels "havana","ensembl",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ type                    : Factor w/ 9 levels "gene","transcript",..: 1 2 3 1 2 3 1 2 3 1 ...
 $ start                   : int  108344807 108344807 108344807 6980784 6980784 6980784 108540067 108540067 108540067 108697865 ...
 $ end                     : int  108347562 108347562 108347562 6981446 6981446 6981446 108540244 108540244 108540244 108699733 ...
 $ score                   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ strand                  : chr  "+" "+" "+" "+" ...
 $ phase                   : int  NA NA NA NA NA NA NA NA NA NA ...
 $ gene_id                 : chr  "ENSMUSG00000104478" "ENSMUSG00000104478" "ENSMUSG00000104478" "ENSMUSG00000104385" ...
 $ gene_version            : chr  "2" "2" "2" "2" ...
 $ gene_name               : chr  "Gm38212" "Gm38212" "Gm38212" "Gm7449" ...
 $ gene_source             : chr  "havana" "havana" "havana" "havana" ...
 $ gene_biotype            : chr  "TEC" "TEC" "TEC" "processed_pseudogene" ...
 $ transcript_id           : chr  NA "ENSMUST00000194081" "ENSMUST00000194081" NA ...
 $ transcript_version      : chr  NA "2" "2" NA ...
 $ transcript_name         : chr  NA "Gm38212-201" "Gm38212-201" NA ...
 $ transcript_source       : chr  NA "havana" "havana" NA ...
 $ transcript_biotype      : chr  NA "TEC" "TEC" NA ...
 $ tag                     : chr  NA "Ensembl_canonical" "Ensembl_canonical" NA ...
 $ transcript_support_level: chr  NA "NA (assigned to previous version 1)" "NA (assigned to previous version 1)" NA ...
 $ exon_number             : chr  NA NA "1" NA ...
 $ exon_id                 : chr  NA NA "ENSMUSE00001337335" NA ...
 $ exon_version            : chr  NA NA "2" NA ...
 $ protein_id              : chr  NA NA NA NA ...
 $ protein_version         : chr  NA NA NA NA ...
 $ ccds_id                 : chr  NA NA NA NA ...
 - attr(*, "pragmas")= chr(0)
  ..- attr(*, "attrcol_fmt")= int 2
 - attr(*, "attrcol_fmt")= int 2
 - attr(*, "ncol0")= int 8
 - attr(*, "ntag")= int 18
 - attr(*, "raw_data")= logi FALSE

# Focus on DTU genes

In [29]:
SIG<-DTU_results[which(DTU_results$adj_pvalue <= 0.05),]

str(SIG)
cat("\n")

'data.frame':	148 obs. of  6 variables:
 $ gene_id   : chr  "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000001700" "ENSMUSG00000002279" ...
 $ lr        : num  11.5 34 29.9 14 18.8 ...
 $ df        : int  1 2 2 1 2 2 3 1 2 4 ...
 $ pvalue    : num  6.78e-04 4.24e-08 3.28e-07 1.79e-04 8.36e-05 ...
 $ adj_pvalue: num  0.036734 0.000019 0.000102 0.014255 0.008211 ...
 $ gene_name : chr  "Loxl3" "Dnajc5" "Gramd3" "Lmf1" ...

In [30]:
SIG_proportions<-DTU_modelled_proportions[which(DTU_modelled_proportions$gene_id%in%SIG$gene_id),]

cat("SIG_proportions\n")
str(SIG_proportions)
cat("\n")

SIG_proportions
'data.frame':	439 obs. of  33 variables:
 $ gene_id    : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ feature_id : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ LM411_R1_t0: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ LM411_R2_t0: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ LM411_R3_t0: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ LM411_R1_t1: num  0.379 0.621 0.323 0.152 0.525 ...
 $ LM411_R2_t1: num  0.379 0.621 0.323 0.152 0.525 ...
 $ LM411_R3_t1: num  0.379 0.621 0.323 0.152 0.525 ...
 $ LM411_R1_t2: num  0.446 0.554 0.339 0.187 0.474 ...
 $ LM411_R2_t2: num  0.446 0.554 0.339 0.187 0.474 ...
 $ LM411_R3_t2: num  0.446 0.554 0.339 0.187 0.474 ...
 $ LM411_R1_t3: num  0.343 0.657 0.374 0.226 0.401 ...
 $ LM411_R2_t3: num  0.343 0.657 0.374 0.226 0.401 ...
 $ LM411_R3_t3: num  0.343 0.657 0.374 0.226 0.401 ...
 $ LM411_R1_t4: num  0.715 0.285 0.361 0.266 0.373 ...
 $ LM411_R2_t4: num  0.715 0.285 0.361 0.266 0.373 ...
 $ LM411_R3_t4: num  0.715 0.285 0.361 0.266 0.373 ...
 $ LM511_R1_t0: num  0.0163 0.9837 0.4084 0.1413 0.4504 ...
 $ LM511_R2_t0: num  0.0163 0.9837 0.4084 0.1413 0.4504 ...
 $ LM511_R3_t0: num  0.0163 0.9837 0.4084 0.1413 0.4504 ...
 $ LM511_R1_t1: num  0.0968 0.9032 0.3209 0.1764 0.5027 ...
 $ LM511_R2_t1: num  0.0968 0.9032 0.3209 0.1764 0.5027 ...
 $ LM511_R3_t1: num  0.0968 0.9032 0.3209 0.1764 0.5027 ...
 $ LM511_R1_t2: num  0.124 0.876 0.334 0.216 0.45 ...
 $ LM511_R2_t2: num  0.124 0.876 0.334 0.216 0.45 ...
 $ LM511_R3_t2: num  0.124 0.876 0.334 0.216 0.45 ...
 $ LM511_R1_t3: num  0.0839 0.9161 0.3646 0.2578 0.3776 ...
 $ LM511_R2_t3: num  0.0839 0.9161 0.3646 0.2578 0.3776 ...
 $ LM511_R3_t3: num  0.0839 0.9161 0.3646 0.2578 0.3776 ...
 $ LM511_R1_t4: num  0.306 0.694 0.35 0.302 0.348 ...
 $ LM511_R2_t4: num  0.306 0.694 0.35 0.302 0.348 ...
 $ LM511_R3_t4: num  0.306 0.694 0.35 0.302 0.348 ...
 $ gene_name  : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...

In [31]:
SIG_proportions.m<-reshape2::melt(SIG_proportions, id.vars=c('gene_id','gene_name','feature_id'), variable.name="sample", value.name="DRIMSeq_modelled_proportions")

cat("SIG_proportions.m_0\n")
str(SIG_proportions.m)
cat("\n")


SIG_proportions.m$treat<-gsub("_.+$","",SIG_proportions.m$sample)
SIG_proportions.m$batch<-gsub("^[^_]+_","",SIG_proportions.m$sample)
SIG_proportions.m$batch<-gsub("_.+$","",SIG_proportions.m$batch)
SIG_proportions.m$time_point<-gsub("^[^_]+_[^_]+_","",SIG_proportions.m$sample)

cat("SIG_proportions.m_1\n")
str(SIG_proportions.m)
cat("\n")

SIG_proportions.m$treat<-factor(SIG_proportions.m$treat, levels=c('LM411','LM511'), ordered=T)
SIG_proportions.m$time_point<-factor(SIG_proportions.m$time_point, levels=c("t0", "t1","t2","t3","t4"), ordered=T)

cat("SIG_proportions.m_2\n")
str(SIG_proportions.m)
cat("\n")

SIG_proportions.m_0
'data.frame':	13170 obs. of  5 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ feature_id                  : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample                      : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...

SIG_proportions.m_1
'data.frame':	13170 obs. of  8 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ feature_id                  : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample                      : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ treat                       : chr  "LM411" "LM411" "LM411" "LM411" ...
 $ batch                       : chr  "R1" "R1" "R1" "R1" ...
 $ time_point                  : chr  "t0" "t0" "t0" "t0" ...

SIG_proportions.m_2
'data.frame':	13170 obs. of  8 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ feature_id                  : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample                      : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ treat                       : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 1 1 1 1 1 1 1 ...
 $ batch                       : chr  "R1" "R1" "R1" "R1" ...
 $ time_point                  : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 1 1 1 1 ...

In [32]:
SIG_proportions.m_subset<-unique(SIG_proportions.m[,-which(colnames(SIG_proportions.m)%in%c('sample','batch'))])


cat("SIG_proportions.m_subset_0\n")
str(SIG_proportions.m_subset)
cat("\n")

SIG_proportions.m_subset_0
'data.frame':	4390 obs. of  6 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ feature_id                  : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.4103 0.1212 0.4685 ...
 $ treat                       : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 1 1 1 1 1 1 1 ...
 $ time_point                  : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 1 1 1 1 ...

# Merge with gene result

In [33]:
SIG_proportions.m_subset<-merge(SIG,SIG_proportions.m_subset, by=c("gene_id","gene_name"))


cat("SIG_proportions.m_subset_1\n")
str(SIG_proportions.m_subset)
cat("\n")

SIG_proportions.m_subset_0
'data.frame':	4390 obs. of  10 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000693" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Loxl3" "Loxl3" ...
 $ lr                          : num  11.5 11.5 11.5 11.5 11.5 ...
 $ df                          : int  1 1 1 1 1 1 1 1 1 1 ...
 $ pvalue                      : num  0.000678 0.000678 0.000678 0.000678 0.000678 ...
 $ adj_pvalue                  : num  0.0367 0.0367 0.0367 0.0367 0.0367 ...
 $ feature_id                  : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000000707" "ENSMUST00000000707" ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.0839 0.4457 0.0968 ...
 $ treat                       : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 2 1 2 2 2 2 2 2 ...
 $ time_point                  : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 4 3 2 2 1 4 3 1 ...

# Subset and transform TPM per replicate

In [34]:
colnames(SIG_proportions.m_subset)[which(colnames(SIG_proportions.m_subset) == 'feature_id')]<-'transcript_id'

cat("SIG_proportions.m_subset_2\n")
str(SIG_proportions.m_subset)
cat("\n")

SIG_proportions.m_subset_2
'data.frame':	4390 obs. of  10 variables:
 $ gene_id                     : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000693" ...
 $ gene_name                   : chr  "Loxl3" "Loxl3" "Loxl3" "Loxl3" ...
 $ lr                          : num  11.5 11.5 11.5 11.5 11.5 ...
 $ df                          : int  1 1 1 1 1 1 1 1 1 1 ...
 $ pvalue                      : num  0.000678 0.000678 0.000678 0.000678 0.000678 ...
 $ adj_pvalue                  : num  0.0367 0.0367 0.0367 0.0367 0.0367 ...
 $ transcript_id               : chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000000707" "ENSMUST00000000707" ...
 $ DRIMSeq_modelled_proportions: num  0.0862 0.9138 0.0839 0.4457 0.0968 ...
 $ treat                       : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 2 1 2 2 2 2 2 2 ...
 $ time_point                  : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 4 3 2 2 1 4 3 1 ...

In [35]:
all_TPM_counts_subset<-all_TPM_counts[which(all_TPM_counts$transcript_id%in%SIG_proportions.m_subset$transcript_id),]

cat("all_TPM_counts_subset_0\n")
str(all_TPM_counts_subset)
cat("\n")

all_TPM_counts_subset_0
'data.frame':	439 obs. of  33 variables:
 $ gene_id      : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ transcript_id: chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ LM411_R1_t0  : num  0 0.13 17.68 10.28 39.96 ...
 $ LM411_R1_t1  : num  0.08 0.19 11.55 11.28 37.65 ...
 $ LM411_R1_t2  : num  0.04 0.19 12.5 12.04 29.94 ...
 $ LM411_R1_t3  : num  0.11 0.24 14.42 16.74 28.6 ...
 $ LM411_R1_t4  : num  0.32 0 14.53 17.99 24.94 ...
 $ LM411_R2_t0  : num  0 0.12 17.49 12.15 37.59 ...
 $ LM411_R2_t1  : num  0 0.21 12.98 11.56 37.82 ...
 $ LM411_R2_t2  : num  0.08 0.14 12.32 12.97 33.17 ...
 $ LM411_R2_t3  : num  0.16 0.11 14.27 15.52 31.5 ...
 $ LM411_R2_t4  : num  0.13 0.1 13.73 18.56 26.9 ...
 $ LM411_R3_t0  : num  0.04 0.11 19.07 9.37 34.32 ...
 $ LM411_R3_t1  : num  0.06 0.09 13.89 11.24 39.41 ...
 $ LM411_R3_t2  : num  0.05 0.25 12.52 12.03 30.47 ...
 $ LM411_R3_t3  : num  0.1 0.24 14.18 16.62 28.56 ...
 $ LM411_R3_t4  : num  0.12 0.08 14.41 20.08 26.1 ...
 $ LM511_R1_t0  : num  0 0.05 17.06 11.05 33.8 ...
 $ LM511_R1_t1  : num  0.13 0.17 10.75 9.75 30.43 ...
 $ LM511_R1_t2  : num  0 0.2 11.9 16.6 31.2 ...
 $ LM511_R1_t3  : num  0 0.26 13.76 20.22 25.61 ...
 $ LM511_R1_t4  : num  0.1 0.18 12.83 22.08 25.73 ...
 $ LM511_R2_t0  : num  0 0.04 17.14 9.25 37.31 ...
 $ LM511_R2_t1  : num  0.04 0.14 10.89 12.09 31.25 ...
 $ LM511_R2_t2  : num  0.08 0.24 12.23 13.99 30.7 ...
 $ LM511_R2_t3  : num  0 0.16 15.49 18.59 27.31 ...
 $ LM511_R2_t4  : num  0.08 0.31 12.15 19.08 24.29 ...
 $ LM511_R3_t0  : num  0 0.13 18.86 12.06 37.09 ...
 $ LM511_R3_t1  : num  0 0.33 12.37 12.15 33.84 ...
 $ LM511_R3_t2  : num  0.1 0.16 12.56 15.09 30.33 ...
 $ LM511_R3_t3  : num  0 0.23 14.37 17.86 25.49 ...
 $ LM511_R3_t4  : num  0 0.31 13.38 22.92 22.46 ...
 $ gene_name    : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...

In [36]:
all_TPM_counts_subset.m<-reshape2::melt(all_TPM_counts_subset, id.vars=c('gene_id','gene_name','transcript_id'), variable.name="sample", value.name="TPM")

cat("all_TPM_counts_subset.m_0\n")
str(all_TPM_counts_subset.m)
cat("\n")


all_TPM_counts_subset.m$treat<-gsub("_.+$","",all_TPM_counts_subset.m$sample)
all_TPM_counts_subset.m$batch<-gsub("^[^_]+_","",all_TPM_counts_subset.m$sample)
all_TPM_counts_subset.m$batch<-gsub("_.+$","",all_TPM_counts_subset.m$batch)
all_TPM_counts_subset.m$time_point<-gsub("^[^_]+_[^_]+_","",all_TPM_counts_subset.m$sample)

cat("all_TPM_counts_subset.m_1\n")
str(all_TPM_counts_subset.m)
cat("\n")

all_TPM_counts_subset.m$treat<-factor(all_TPM_counts_subset.m$treat, levels=c('LM411','LM511'), ordered=T)
all_TPM_counts_subset.m$time_point<-factor(all_TPM_counts_subset.m$time_point, levels=c("t0", "t1","t2","t3","t4"), ordered=T)

cat("all_TPM_counts_subset.m_2\n")
str(all_TPM_counts_subset.m)
cat("\n")

all_TPM_counts_subset.m_0
'data.frame':	13170 obs. of  5 variables:
 $ gene_id      : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name    : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ transcript_id: chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample       : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ TPM          : num  0 0.13 17.68 10.28 39.96 ...

all_TPM_counts_subset.m_1
'data.frame':	13170 obs. of  8 variables:
 $ gene_id      : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name    : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ transcript_id: chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample       : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ TPM          : num  0 0.13 17.68 10.28 39.96 ...
 $ treat        : chr  "LM411" "LM411" "LM411" "LM411" ...
 $ batch        : chr  "R1" "R1" "R1" "R1" ...
 $ time_point   : chr  "t0" "t0" "t0" "t0" ...

all_TPM_counts_subset.m_2
'data.frame':	13170 obs. of  8 variables:
 $ gene_id      : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000000826" "ENSMUSG00000000826" ...
 $ gene_name    : chr  "Loxl3" "Loxl3" "Dnajc5" "Dnajc5" ...
 $ transcript_id: chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...
 $ sample       : Factor w/ 30 levels "LM411_R1_t0",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ TPM          : num  0 0.13 17.68 10.28 39.96 ...
 $ treat        : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 1 1 1 1 1 1 1 ...
 $ batch        : chr  "R1" "R1" "R1" "R1" ...
 $ time_point   : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 1 1 1 1 ...

#  Calculate the Maximum Absolute Proportion Difference ($\text{Max } \Delta \pi$)

In [41]:
# Rename and prepare the input data for calculation
dtu_prioritization_data <- SIG_proportions.m_subset %>%
    dplyr::rename(
        proportion = DRIMSeq_modelled_proportions,
        feature_id = transcript_id
    ) %>%
    # Ensure factors are in the correct comparison order
    mutate(
        treat = factor(treat, levels = c("LM411", "LM511")),
        time_point = factor(time_point, levels = c("t0", "t1", "t2", "t3", "t4"))
    ) %>%
    # Select only necessary columns
    dplyr::select(gene_id, gene_name, feature_id, proportion, treat, time_point, adj_pvalue)


# Calculate the Max Absolute Proportion Difference (Max Δπ)
DTU_prioritization_results <- dtu_prioritization_data %>%
    # Step 1: Pivot data to have LM411 and LM511 proportions in separate columns
    pivot_wider(
        id_cols = c(gene_id, gene_name, feature_id, time_point, adj_pvalue),
        names_from = treat,
        values_from = proportion
    ) %>%
    # Step 2: Calculate the absolute difference in proportion (pi_LM511 - pi_LM411)
    mutate(
        Delta_Proportion = LM511 - LM411,
        Abs_Delta_Proportion = abs(Delta_Proportion)
    ) %>%
    # Step 3: Group by gene and time point to find the maximum difference
    group_by(gene_id, gene_name, time_point, adj_pvalue) %>%
    summarise(
        # The transcript responsible for the largest shift
        Max_Shift_Transcript = feature_id[which.max(Abs_Delta_Proportion)],
        # The maximum absolute difference for the gene at this time point
        Max_Abs_Delta_pi = max(Abs_Delta_Proportion, na.rm = TRUE),
        # The actual signed shift for the max transcript (LM511 - LM411)
        Max_Delta_pi_Signed = Delta_Proportion[which.max(Abs_Delta_Proportion)],
        .groups = 'drop'
    ) %>%
    # Step 4: Group by gene only to find the largest shift *across all time points*
    group_by(gene_id, gene_name) %>%
    summarise(
        Overall_Max_Delta_pi = max(Max_Abs_Delta_pi, na.rm = TRUE),
        Time_Point_of_Max_Shift = time_point[which.max(Max_Abs_Delta_pi)],
        # Using indexing [1] to safely retrieve the adjusted p-value
        Adj_Pvalue = adj_pvalue[1], 
        .groups = 'drop'
    ) %>%
    # Step 5: Arrange results by the magnitude of the shift (descending)
    arrange(desc(Overall_Max_Delta_pi), Adj_Pvalue)

# Display the top 10 prioritized genes
print("Top 10 DTU Genes Prioritized by Shift Magnitude (Max Δπ):")
print(head(DTU_prioritization_results, 10))

[1] "Top 10 DTU Genes Prioritized by Shift Magnitude (Max Δπ):"
# A tibble: 10 × 5
   gene_id      gene_name Overall_Max_Delta_pi Time_Point_of_Max_Sh…¹ Adj_Pvalue
   <chr>        <chr>                    <dbl> <ord>                       <dbl>
 1 ENSMUSG0000… Dnah10                   0.637 t0                       0.0361
 2 ENSMUSG0000… Pla2g4c                  0.606 t2                       0.0406
 3 ENSMUSG0000… NA                       0.471 t2                       0.0387
 4 ENSMUSG0000… Loxl3                    0.409 t4                       0.0367
 5 ENSMUSG0000… Cage1                    0.401 t0                       0.00789
 6 ENSMUSG0000… Stard9                   0.333 t3                       0.0302
 7 ENSMUSG0000… Nrn1                     0.319 t2                       0.00367
 8 ENSMUSG0000… Oxr1                     0.303 t3                       0.000396
 9 ENSMUSG0000… NA                       0.296 t2                       0.00313
10 ENSMUSG0000… Mcm9                     0.293 t1                       0.00412
# ℹ abbreviated name: ¹​Time_Point_of_Max_Shift

## Merge with the transcript data

In [45]:
# --- 1. Load/Prepare Data (Assuming the corrected prioritization table is final) ---

# DTU_prioritization_results_final is the gene-level summary table (from previous step)
# SIG_proportions.m_subset is the transcript-level proportions table

# Clean and rename the proportions data slightly before merging
proportions_data_clean <- SIG_proportions.m_subset %>%
    dplyr::rename(
        proportion = DRIMSeq_modelled_proportions,
        feature_id = transcript_id
    ) %>%
    # Ensure all gene identifiers are clean (though they should be already)
    mutate(gene_name = as.character(gene_name)) %>%
    dplyr::select(
        gene_id, gene_name, feature_id, 
        proportion, treat, time_point, 
        raw_pvalue = pvalue, # Keep raw p-value for reference
        adj_pvalue # Keep the gene-level FDR
    )

# Clean the prioritization table for merging
prioritization_to_merge <- DTU_prioritization_results %>%
    # Select only the new key metrics for the merge
    dplyr::select(
        gene_id, gene_name, 
        Overall_Max_Delta_pi, 
        Time_Point_of_Max_Shift
    )

# --- 2. Perform the Merge ---

# Perform a left join to attach the prioritization metrics to every transcript row
# The join keys are gene_id and gene_name
Transcript_DTU_Analysis_Table <- proportions_data_clean %>%
    left_join(prioritization_to_merge, by = c("gene_id", "gene_name")) %>%
    
    # Sort the final table by the prioritization metric
    arrange(desc(Overall_Max_Delta_pi), time_point, treat, feature_id)

# --- 3. Review the Final Merged Table ---

cat("Structure of the final merged transcript table:\n")
str(Transcript_DTU_Analysis_Table)

Structure of the final merged transcript table:
'data.frame':	4390 obs. of  10 variables:
 $ gene_id                : chr  "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" ...
 $ gene_name              : chr  "Dnah10" "Dnah10" "Dnah10" "Dnah10" ...
 $ feature_id             : chr  "ENSMUST00000058440" "ENSMUST00000141137" "ENSMUST00000196708" "ENSMUST00000058440" ...
 $ proportion             : num  6.37e-01 1.73e-01 1.90e-01 1.31e-09 4.89e-01 ...
 $ treat                  : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 2 2 2 1 1 1 2 ...
 $ time_point             : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 2 2 2 2 ...
 $ raw_pvalue             : num  0.00066 0.00066 0.00066 0.00066 0.00066 ...
 $ adj_pvalue             : num  0.0361 0.0361 0.0361 0.0361 0.0361 ...
 $ Overall_Max_Delta_pi   : num  0.637 0.637 0.637 0.637 0.637 ...
 $ Time_Point_of_Max_Shift: Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 1 1 1 1 ...

## Subset for the time points in which the time shift is max

In [50]:
# Assuming Transcript_DTU_Analysis_Table is the merged table from the previous step.
# If you are using the originally merged table (without the final column names), 
# replace the column names accordingly.

# The Time_Point_of_Max_Shift value is repeated for every row of a gene, 
# so we can filter based on that value.

# Ensure the columns used for comparison are character or factor
Transcript_DTU_Analysis_Table <- Transcript_DTU_Analysis_Table %>%
  mutate(
    time_point = as.character(time_point),
    Time_Point_of_Max_Shift = as.character(Time_Point_of_Max_Shift)
  )

# Subset the data frame
Max_Shift_TimePoint_Subset <- Transcript_DTU_Analysis_Table %>%
  # Filter to keep only the rows where the current time_point matches 
  # the gene's Time_Point_of_Max_Shift
  filter(time_point == Time_Point_of_Max_Shift) %>%
  
  # Clean up the sorting and select final columns for review
  arrange(desc(Overall_Max_Delta_pi), time_point, treat, feature_id) %>%
  
  # Convert time_point back to ordered factor for final use if needed
  mutate(
    time_point = factor(time_point, levels = c("t0", "t1", "t2", "t3", "t4"), ordered = TRUE),
    Time_Point_of_Max_Shift = factor(Time_Point_of_Max_Shift, levels = c("t0", "t1", "t2", "t3", "t4"), ordered = TRUE)
  )

colnames(Max_Shift_TimePoint_Subset)[which(colnames(Max_Shift_TimePoint_Subset) == 'feature_id')]<-'transcript_id'
# Review the structure and the top rows of the subsetted data
cat("Structure of the Max Shift Time Point Subset:\n")
str(Max_Shift_TimePoint_Subset)

Structure of the Max Shift Time Point Subset:
'data.frame':	878 obs. of  10 variables:
 $ gene_id                : chr  "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" ...
 $ gene_name              : chr  "Dnah10" "Dnah10" "Dnah10" "Dnah10" ...
 $ transcript_id          : chr  "ENSMUST00000058440" "ENSMUST00000141137" "ENSMUST00000196708" "ENSMUST00000058440" ...
 $ proportion             : num  6.37e-01 1.73e-01 1.90e-01 1.31e-09 4.89e-01 ...
 $ treat                  : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 2 2 2 1 1 1 2 ...
 $ time_point             : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 3 3 3 3 ...
 $ raw_pvalue             : num  0.00066 0.00066 0.00066 0.00066 0.00066 ...
 $ adj_pvalue             : num  0.0361 0.0361 0.0361 0.0361 0.0361 ...
 $ Overall_Max_Delta_pi   : num  0.637 0.637 0.637 0.637 0.637 ...
 $ Time_Point_of_Max_Shift: Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 3 3 3 3 ...

In [49]:
Max_Shift_TimePoint_Subset[which(Max_Shift_TimePoint_Subset$gene_name == 'Dnah10'),]

  gene_id            gene_name feature_id         proportion   treat time_point
1 ENSMUSG00000038011 Dnah10    ENSMUST00000058440 6.373874e-01 LM411 t0
2 ENSMUSG00000038011 Dnah10    ENSMUST00000141137 1.726798e-01 LM411 t0
3 ENSMUSG00000038011 Dnah10    ENSMUST00000196708 1.899328e-01 LM411 t0
4 ENSMUSG00000038011 Dnah10    ENSMUST00000058440 1.312152e-09 LM511 t0
5 ENSMUSG00000038011 Dnah10    ENSMUST00000141137 4.892590e-01 LM511 t0
6 ENSMUSG00000038011 Dnah10    ENSMUST00000196708 5.107410e-01 LM511 t0
  raw_pvalue   adj_pvalue Overall_Max_Delta_pi Time_Point_of_Max_Shift
1 0.0006603655 0.03612855 0.6373874            t0
2 0.0006603655 0.03612855 0.6373874            t0
3 0.0006603655 0.03612855 0.6373874            t0
4 0.0006603655 0.03612855 0.6373874            t0
5 0.0006603655 0.03612855 0.6373874            t0
6 0.0006603655 0.03612855 0.6373874            t0

# Calculation of Differential Proportion ($\Delta \pi$)

In [52]:
# Assuming Max_Shift_TimePoint_Subset is the filtered table containing only the 
# time point of max shift for each gene.

# --- 1. Calculate Delta Pi (Δπ) in a temporary table ---
# This temporary table will be a wide format, but only for the necessary columns.
Delta_pi_Temp <- Max_Shift_TimePoint_Subset %>%
    
    # Select key identifiers and the proportion/treatment columns
    dplyr::select(gene_id, gene_name, transcript_id, treat, proportion) %>%
    
    # Pivot to align LM411 and LM511 proportions
    pivot_wider(
        names_from = treat,
        values_from = proportion
    ) %>%
    
    # Calculate Delta pi (LM511 - LM411)
    mutate(
        Delta_pi = LM511 - LM411
    ) %>%
    
    # Select only the identifiers and the new Delta_pi column
    dplyr::select(gene_id, transcript_id, Delta_pi)


# --- 2. Merge Delta Pi back into the original long format ---

# Merge the Delta_pi column back into the Max_Shift_TimePoint_Subset
Max_Shift_TimePoint_with_Delta <- Max_Shift_TimePoint_Subset %>%
    
    # Perform a left join on the gene and transcript identifiers
    left_join(Delta_pi_Temp, by = c("gene_id", "transcript_id")) %>%
    
    # Re-sort for better visualization and grouping
    arrange(desc(Overall_Max_Delta_pi), time_point, treat, transcript_id)

# Review the structure and the top rows to ensure the Delta_pi column is added
cat("Structure of the final data frame with Delta_pi:\n")
str(Max_Shift_TimePoint_with_Delta)

Structure of the final data frame with Delta_pi:
'data.frame':	878 obs. of  11 variables:
 $ gene_id                : chr  "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" "ENSMUSG00000038011" ...
 $ gene_name              : chr  "Dnah10" "Dnah10" "Dnah10" "Dnah10" ...
 $ transcript_id          : chr  "ENSMUST00000058440" "ENSMUST00000141137" "ENSMUST00000196708" "ENSMUST00000058440" ...
 $ proportion             : num  6.37e-01 1.73e-01 1.90e-01 1.31e-09 4.89e-01 ...
 $ treat                  : Ord.factor w/ 2 levels "LM411"<"LM511": 1 1 1 2 2 2 1 1 1 2 ...
 $ time_point             : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 3 3 3 3 ...
 $ raw_pvalue             : num  0.00066 0.00066 0.00066 0.00066 0.00066 ...
 $ adj_pvalue             : num  0.0361 0.0361 0.0361 0.0361 0.0361 ...
 $ Overall_Max_Delta_pi   : num  0.637 0.637 0.637 0.637 0.637 ...
 $ Time_Point_of_Max_Shift: Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 1 1 1 1 1 3 3 3 3 ...
 $ Delta_pi               : num  -0.637 0.317 0.321 -0.637 0.317 ...

# Annotate results with transcript biotype and tag

In [55]:
transcript_id_array <- unique(Max_Shift_TimePoint_with_Delta$transcript_id)

# Create a lookup table for the original COORD index (1, 2, 3, ...)
coord_mapping <- data.frame(
    transcript_id = transcript_id_array,
    COORD = 1:length(transcript_id_array)
)

# --- 2. Vectorized Filtering and Joining ---

# Filter the large GTF table once for all relevant transcripts, 
# then rename the column and join the COORD index back.

REP_efficient <- ensembl_gtf %>%
    
    # 2a. Efficiently filter to keep only transcripts present in the target array
    # AND filter out 'gene' features in one pass.
    filter(transcript_id %in% transcript_id_array,
           type != 'gene') %>%
    
    # 2b. Add the COORD index by joining the mapping table
    left_join(coord_mapping, by = "transcript_id") %>%
    
    # 2c. Rename the 'seqid' column to 'seqnames'
    #rename(seqnames = seqid) %>%
    
    # Optional: Arrange to match the reverse order of the original (due to rbind(..., REP))
    # If the exact row order isn't critical, you can skip this.
    arrange(desc(COORD)) 

# The resulting data frame REP_efficient is the same as the result of your loop,
# but constructed in a single, high-speed vectorized operation.

cat("Efficient creation of REP is complete. Resulting structure:\n")
cat(str(REP_efficient))

Efficient creation of REP is complete. Resulting structure:
'data.frame':	11684 obs. of  27 variables:
 $ seqid                   : Factor w/ 38 levels "1","2","X","3",..: 8 8 8 8 8 8 8 8 8 8 ...
 $ source                  : Factor w/ 8 levels "havana","ensembl",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ type                    : Factor w/ 9 levels "gene","transcript",..: 2 3 4 5 3 4 3 4 3 4 ...
 $ start                   : int  5065244 5065244 5065287 5065287 5069402 5069402 5070209 5070209 5070543 5070543 ...
 $ end                     : int  5082932 5065335 5065335 5065289 5069537 5069537 5070253 5070253 5070646 5070646 ...
 $ score                   : num  NA NA NA NA NA NA NA NA NA NA ...
 $ strand                  : chr  "+" "+" "+" "+" ...
 $ phase                   : int  NA NA 0 0 NA 2 NA 1 NA 1 ...
 $ gene_id                 : chr  "ENSMUSG00000030435" "ENSMUSG00000030435" "ENSMUSG00000030435" "ENSMUSG00000030435" ...
 $ gene_version            : chr  "18" "18" "18" "18" ...
 $ gene_name               : chr  "U2af2" "U2af2" "U2af2" "U2af2" ...
 $ gene_source             : chr  "ensembl_havana" "ensembl_havana" "ensembl_havana" "ensembl_havana" ...
 $ gene_biotype            : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ transcript_id           : chr  "ENSMUST00000209099" "ENSMUST00000209099" "ENSMUST00000209099" "ENSMUST00000209099" ...
 $ transcript_version      : chr  "2" "2" "2" "2" ...
 $ transcript_name         : chr  "U2af2-208" "U2af2-208" "U2af2-208" "U2af2-208" ...
 $ transcript_source       : chr  "ensembl_havana" "ensembl_havana" "ensembl_havana" "ensembl_havana" ...
 $ transcript_biotype      : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ tag                     : chr  "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" ...
 $ exon_number             : chr  NA "1" "1" "1" ...
 $ exon_id                 : chr  NA "ENSMUSE00001380707" NA NA ...
 $ exon_version            : chr  NA "2" NA NA ...
 $ protein_id              : chr  NA NA "ENSMUSP00000147013" NA ...
 $ protein_version         : chr  NA NA "2" NA ...
 $ ccds_id                 : chr  "CCDS57476" "CCDS57476" "CCDS57476" "CCDS57476" ...
 $ COORD                   : int  439 439 439 439 439 439 439 439 439 439 ...
 - attr(*, "pragmas")= chr(0)
  ..- attr(*, "attrcol_fmt")= int 2
 - attr(*, "attrcol_fmt")= int 2
 - attr(*, "ncol0")= int 8
 - attr(*, "ntag")= int 18
 - attr(*, "raw_data")= logi FALSE

In [56]:
summary(as.factor(REP$transcript_biotype))

                        lncRNA        nonsense_mediated_decay
                            79                            591
                protein_coding protein_coding_CDS_not_defined
                         10469                            127
            protein_coding_LoF                retained_intron
                            80                            338

In [58]:
names(summary(as.factor(REP$transcript_biotype)))

[1] "lncRNA"                         "nonsense_mediated_decay"
[3] "protein_coding"                 "protein_coding_CDS_not_defined"
[5] "protein_coding_LoF"             "retained_intron"

In [59]:
REP$transcript_biotype<-factor(REP$transcript_biotype,
                                     levels=c("protein_coding","protein_coding_CDS_not_defined","protein_coding_LoF","nonsense_mediated_decay","retained_intron","lncRNA"),
                                     ordered=T)

In [60]:
REP_subset<-unique(REP[which(REP$type == 'transcript'),which(colnames(REP)%in%c('transcript_id','transcript_biotype','tag','transcript_support_level'))])



cat(str(REP_subset))

'data.frame':	439 obs. of  4 variables:
 $ transcript_id           : chr  "ENSMUST00000209099" "ENSMUST00000005041" "ENSMUST00000090381" "ENSMUST00000052266" ...
 $ transcript_biotype      : Ord.factor w/ 6 levels "protein_coding"<..: 1 1 1 1 1 1 4 1 1 1 ...
 $ tag                     : chr  "Ensembl_canonical" "gencode_basic" "gencode_basic" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 1)" "1 (assigned to previous version 14)" "1 (assigned to previous version 10)" "1 (assigned to previous version 14)" ...

In [62]:
Max_Shift_TimePoint_with_Delta_annotated<-merge(Max_Shift_TimePoint_with_Delta,
                                      REP_subset,
                                      by="transcript_id")


cat("Max_Shift_TimePoint_with_Delta_annotated\n")
cat(str(Max_Shift_TimePoint_with_Delta_annotated))

Max_Shift_TimePoint_with_Delta_annotated
'data.frame':	878 obs. of  14 variables:
 $ transcript_id           : chr  "ENSMUST00000000707" "ENSMUST00000000707" "ENSMUST00000002469" "ENSMUST00000002469" ...
 $ gene_id                 : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000002396" "ENSMUSG00000002396" ...
 $ gene_name               : chr  "Loxl3" "Loxl3" "Ocel1" "Ocel1" ...
 $ proportion              : num  0.715 0.306 0.326 0.261 0.667 ...
 $ treat                   : Ord.factor w/ 2 levels "LM411"<"LM511": 1 2 1 2 1 2 1 2 1 2 ...
 $ time_point              : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 5 5 5 5 2 2 2 2 5 5 ...
 $ raw_pvalue              : num  6.78e-04 6.78e-04 8.36e-05 8.36e-05 2.50e-04 ...
 $ adj_pvalue              : num  0.03673 0.03673 0.00821 0.00821 0.01802 ...
 $ Overall_Max_Delta_pi    : num  0.4091 0.4091 0.0726 0.0726 0.0425 ...
 $ Time_Point_of_Max_Shift : Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 5 5 5 5 2 2 2 2 5 5 ...
 $ Delta_pi                : num  -0.4091 -0.4091 -0.065 -0.065 -0.0425 ...
 $ transcript_biotype      : Ord.factor w/ 6 levels "protein_coding"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ tag                     : chr  "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" ...

# Identifying Functional Isoform Switches

In [67]:

# Use the final annotated data frame
df_annotated <- Max_Shift_TimePoint_with_Delta_annotated

# --- 1. Identify the Most Expressed Transcript (MET) and its Biotype per Condition ---
MET_by_condition <- df_annotated %>%
    
    # Group by gene, time point, and treatment
    group_by(gene_id, gene_name, Time_Point_of_Max_Shift, treat) %>%
    
    # Find the row with the maximum proportion (the MET)
    slice_max(order_by = proportion, n = 1, with_ties = FALSE) %>% 
    ungroup() %>%
    
    # Select the key MET information
    dplyr::select(
        gene_id, gene_name, Time_Point_of_Max_Shift, treat,
        MET_ID = transcript_id,
        MET_Biotype = transcript_biotype
    )


# --- 2. Pivot to Compare METs Side-by-Side and Filter ---
Functional_Switch_Summary_DF <- MET_by_condition %>%
    
    # Pivot to align LM411 and LM511 METs side-by-side
    pivot_wider(
        id_cols = c(gene_id, gene_name, Time_Point_of_Max_Shift),
        names_from = treat,
        values_from = c(MET_ID, MET_Biotype)
    ) %>%
    
    # Check for switches
    mutate(
        ID_Switched = (MET_ID_LM411 != MET_ID_LM511),
        Biotype_Switched = (MET_Biotype_LM411 != MET_Biotype_LM511)
    ) %>%
    
    # Filter to keep ONLY genes where BOTH the ID and Biotype switched
    filter(ID_Switched == TRUE, Biotype_Switched == TRUE) %>%
    
    # Join the overall Max Delta Pi metric back for final prioritization
    left_join(
        df_annotated %>% 
            dplyr::select(gene_id, Overall_Max_Delta_pi) %>% 
            distinct(), 
        by = "gene_id"
    ) %>%
    
    # --- 3. Final Ordering and Selection ---
    
    # Sort by the magnitude of the shift
    arrange(desc(Overall_Max_Delta_pi)) %>%
    
    # Reorder and rename columns for a clean presentation
    dplyr::select(
        Gene_Symbol = gene_name,
        Gene_ID = gene_id,
        Max_Delta_pi = Overall_Max_Delta_pi,
        Max_Shift_TimePoint = Time_Point_of_Max_Shift,
        
        # Side-by-side comparison columns:
        MET_ID_LM411,
        MET_Biotype_LM411,
        MET_ID_LM511,
        MET_Biotype_LM511,
        
        # Confirmation flags
        ID_Switched,
        Biotype_Switched
    ) %>%
    
    # 4. EXPLICIT CONVERSION TO BASE R DATA FRAME
    as.data.frame()

# Return the final data frame
print("Data Frame of Genes with Functional Switches (MET ID & Biotype Changed):")
cat(str(Functional_Switch_Summary_DF))

[1] "Data Frame of Genes with Functional Switches (MET ID & Biotype Changed):"
'data.frame':	7 obs. of  10 variables:
 $ Gene_Symbol        : chr  "Dnah10" "Stard9" "Zfp287" "Gm1043" ...
 $ Gene_ID            : chr  "ENSMUSG00000038011" "ENSMUSG00000033705" "ENSMUSG00000005267" "ENSMUSG00000117286" ...
 $ Max_Delta_pi       : num  0.6374 0.3327 0.2643 0.0787 0.0482 ...
 $ Max_Shift_TimePoint: Ord.factor w/ 5 levels "t0"<"t1"<"t2"<..: 1 4 2 2 5 5 5
 $ MET_ID_LM411       : chr  "ENSMUST00000058440" "ENSMUST00000180041" "ENSMUST00000005399" "ENSMUST00000232332" ...
 $ MET_Biotype_LM411  : Ord.factor w/ 6 levels "protein_coding"<..: 1 1 1 1 1 4 4
 $ MET_ID_LM511       : chr  "ENSMUST00000196708" "ENSMUST00000154193" "ENSMUST00000149228" "ENSMUST00000213782" ...
 $ MET_Biotype_LM511  : Ord.factor w/ 6 levels "protein_coding"<..: 5 4 4 5 2 1 1
 $ ID_Switched        : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ Biotype_Switched   : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...

In [71]:
Functional_Switch_Summary_DF

  Gene_Symbol Gene_ID            Max_Delta_pi Max_Shift_TimePoint
1 Dnah10      ENSMUSG00000038011 0.63738743   t0
2 Stard9      ENSMUSG00000033705 0.33267304   t3
3 Zfp287      ENSMUSG00000005267 0.26434146   t1
4 Gm1043      ENSMUSG00000117286 0.07869132   t1
5 Rer1        ENSMUSG00000029048 0.04824699   t4
6 Brd2        ENSMUSG00000024335 0.04595970   t4
7 Dnajc5      ENSMUSG00000000826 0.03557331   t4
  MET_ID_LM411       MET_Biotype_LM411       MET_ID_LM511
1 ENSMUST00000058440 protein_coding          ENSMUST00000196708
2 ENSMUST00000180041 protein_coding          ENSMUST00000154193
3 ENSMUST00000005399 protein_coding          ENSMUST00000149228
4 ENSMUST00000232332 protein_coding          ENSMUST00000213782
5 ENSMUST00000030914 protein_coding          ENSMUST00000149796
6 ENSMUST00000154232 nonsense_mediated_decay ENSMUST00000095347
7 ENSMUST00000116365 nonsense_mediated_decay ENSMUST00000072334
  MET_Biotype_LM511              ID_Switched Biotype_Switched
1 retained_intron                TRUE        TRUE
2 nonsense_mediated_decay        TRUE        TRUE
3 nonsense_mediated_decay        TRUE        TRUE
4 retained_intron                TRUE        TRUE
5 protein_coding_CDS_not_defined TRUE        TRUE
6 protein_coding                 TRUE        TRUE
7 protein_coding                 TRUE        TRUE

# SAVE intermediate

In [72]:
setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/")

In [74]:
# --- Script to Save Final Analysis Data Frames as TSV Files ---

# Prerequisites: Ensure the following data frames exist in your R environment:
# 1. Functional_Switch_Summary_DF (Wide format, top functional switches)
# 2. Max_Shift_TimePoint_with_Delta_annotated (Long format, all transcripts at Max Shift TP)
# 3. all_TPM_counts_subset.m (Input counts data, if required for verification)

# Note on TSV format:
# We use write.table() for maximum control, setting sep="\t" for TSV format,
# and ensuring row names are not written to keep the file clean.

# --- 1. Save Functional Switch Summary Data Frame ---
# This is the small, prioritized list of the most important genes.
write.table(
    Functional_Switch_Summary_DF,
    file = "Functional_Switch_Summary.tsv",
    sep = "\t",
    row.names = FALSE,
    quote = FALSE,
    na = "" # Write empty strings for NA values
)
cat("Saved 'Functional_Switch_Summary_DF' to Functional_Switch_Summary.tsv\n")

# --- 2. Save Full Annotated Data Frame (Long Format) ---
# This is the main, comprehensive table of all significant transcripts at their critical time point.
write.table(
    Max_Shift_TimePoint_with_Delta_annotated,
    file = "Max_Shift_Annotated_Transcripts.tsv",
    sep = "\t",
    row.names = FALSE,
    quote = FALSE,
    na = ""
)
cat("Saved 'Max_Shift_TimePoint_with_Delta_annotated' to Max_Shift_Annotated_Transcripts.tsv\n")


# --- 3. Save the Subsetted TPM Counts Data Frame ---
# This preserves the raw TPM data used for the subset analysis.
write.table(
    all_TPM_counts_subset.m,
    file = "TPM_Counts_Subset.tsv",
    sep = "\t",
    row.names = FALSE,
    quote = FALSE,
    na = ""
)

cat("Saved 'all_TPM_counts_subset.m' to TPM_Counts_Subset.tsv\n")

write.table(
    REP,
    file = "REP_Subset.tsv",
    sep = "\t",
    row.names = FALSE,
    quote = FALSE,
    na = ""
)
cat("Saved 'REP' to REP_Subset.tsv\n")

cat("\nAll three data frames have been successfully saved as TSV files.\n")

Saved 'Functional_Switch_Summary_DF' to Functional_Switch_Summary.tsv
Saved 'Max_Shift_TimePoint_with_Delta_annotated' to Max_Shift_Annotated_Transcripts.tsv
Saved 'all_TPM_counts_subset.m' to TPM_Counts_Subset.tsv
Saved 'REP' to REP_Subset.tsv

All three data frames have been successfully saved as TSV files.

# Visualization

In [2]:
# =========================================================================
# === USER REQUEST: CLEAR WORKSPACE AND RELOAD FILES FOR VISUALIZATION ===
# =========================================================================

cat("\nClearing the R workspace now...\n")
# Clear all objects from the current environment
rm(list = ls())
cat("Workspace cleared. Objects will now be reloaded.\n")

# Load data.table for faster reading (as requested by user)
library(data.table)

setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/")

# Reload the four saved data frames using data.table::fread()
# fread() is much faster and automatically detects the TSV format.
# We convert back to a base R data.frame for compatibility with previous workflows.

final_switch_summary <- as.data.frame(fread("Functional_Switch_Summary.tsv", header = TRUE))
cat("Reloaded 'Functional_Switch_Summary.tsv' into 'final_switch_summary' (using fread)\n")

max_shift_long_data <- as.data.frame(fread("Max_Shift_Annotated_Transcripts.tsv", header = TRUE))
cat("Reloaded 'Max_Shift_Annotated_Transcripts.tsv' into 'max_shift_long_data' (using fread)\n")



gtf_subset_rep <- as.data.frame(fread("REP_Subset.tsv", header = TRUE))
cat("Reloaded 'REP_Subset.tsv' into 'gtf_subset_rep' (using fread)\n")

cat("\nReloading complete. You can now begin visualization using the four new objects.\n")

Clearing the R workspace now...
Workspace cleared. Objects will now be reloaded.
Reloaded 'Functional_Switch_Summary.tsv' into 'final_switch_summary' (using fread)
Reloaded 'Max_Shift_Annotated_Transcripts.tsv' into 'max_shift_long_data' (using fread)
Reloaded 'REP_Subset.tsv' into 'gtf_subset_rep' (using fread)

Reloading complete. You can now begin visualization using the four new objects.

In [7]:
str(max_shift_long_data)

'data.frame':	878 obs. of  14 variables:
 $ transcript_id           : chr  "ENSMUST00000000707" "ENSMUST00000000707" "ENSMUST00000002469" "ENSMUST00000002469" ...
 $ gene_id                 : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000002396" "ENSMUSG00000002396" ...
 $ gene_name               : chr  "Loxl3" "Loxl3" "Ocel1" "Ocel1" ...
 $ proportion              : num  0.715 0.306 0.326 0.261 0.667 ...
 $ treat                   : chr  "LM411" "LM511" "LM411" "LM511" ...
 $ time_point              : chr  "t4" "t4" "t4" "t4" ...
 $ raw_pvalue              : num  6.78e-04 6.78e-04 8.36e-05 8.36e-05 2.50e-04 ...
 $ adj_pvalue              : num  0.03673 0.03673 0.00821 0.00821 0.01802 ...
 $ Overall_Max_Delta_pi    : num  0.4091 0.4091 0.0726 0.0726 0.0425 ...
 $ Time_Point_of_Max_Shift : chr  "t4" "t4" "t4" "t4" ...
 $ Delta_pi                : num  -0.4091 -0.4091 -0.065 -0.065 -0.0425 ...
 $ transcript_biotype      : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ tag                     : chr  "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" ...

In [4]:
normalized_counts_transcript<-read.table(file="nor_counts_transcripts.tsv", sep="\t", header=T)


cat("\nnormalized_counts_transcript\n")
cat(str(normalized_counts_transcript))
cat("\n")

normalized_counts_transcript
'data.frame':	71955 obs. of  30 variables:
 $ LM411_R1_t0: num  5891.36 61.28 0 2.19 0 ...
 $ LM411_R1_t1: num  6790.94 644.54 121.64 4.22 0 ...
 $ LM411_R1_t2: num  6808.6 1830.8 138.7 8.1 0 ...
 $ LM411_R1_t3: num  7021.42 1958.26 297.9 4.5 1.12 ...
 $ LM411_R1_t4: num  8008.8 2228.2 236.7 1.5 0 ...
 $ LM411_R2_t0: num  5467.66 42.29 0 2.49 0 ...
 $ LM411_R2_t1: num  6693 521 111 0 0 ...
 $ LM411_R2_t2: num  6449.22 1655.19 131.04 8.62 5.17 ...
 $ LM411_R2_t3: num  7439.13 1901.88 131.09 2.26 3.39 ...
 $ LM411_R2_t4: num  7794.581 1975.764 405.806 3.874 0.969 ...
 $ LM411_R3_t0: num  5322.26 49.92 0 6.77 1.69 ...
 $ LM411_R3_t1: num  6842.784 539.6 32.203 3.927 0.785 ...
 $ LM411_R3_t2: num  6508.71 1589.06 143.66 1.95 4.89 ...
 $ LM411_R3_t3: num  7608.11 1942.36 190.86 5.27 1.05 ...
 $ LM411_R3_t4: num  8055.07 2230.2 219.14 3.61 0 ...
 $ LM511_R1_t0: num  4897.06 42.99 0 9.67 0 ...
 $ LM511_R1_t1: num  7257.71 624.15 168.72 9.75 0 ...
 $ LM511_R1_t2: num  7859.3 1697.97 244.3 4.05 1.01 ...
 $ LM511_R1_t3: num  8937 1906 258 2 1 ...
 $ LM511_R1_t4: num  8892.15 2020.12 324.44 5.65 1.13 ...
 $ LM511_R2_t0: num  5927.8 49.7 18.3 10.1 0 ...
 $ LM511_R2_t1: num  7625.1 688.6 82.1 11.2 0 ...
 $ LM511_R2_t2: num  8043.91 1628.79 151.43 7.21 4.51 ...
 $ LM511_R2_t3: num  9356.98 1823.66 232.81 2.35 2.35 ...
 $ LM511_R2_t4: num  8176.53 2065.34 368.38 2.83 2.12 ...
 $ LM511_R3_t0: num  5270.9 11.3 38.9 15.4 0 ...
 $ LM511_R3_t1: num  7684.5 596.6 74.4 17.2 0 ...
 $ LM511_R3_t2: num  8604.08 1646.06 144.2 4.44 5.55 ...
 $ LM511_R3_t3: num  9884.37 1977.73 220.34 4.26 2.13 ...
 $ LM511_R3_t4: num  8914.18 2113.99 413.09 6.77 1.13 ...

In [5]:
str(row.names(normalized_counts_transcript))
cat("\n")

 chr [1:71955] "ENSMUST00000000001" "ENSMUST00000000028" ...

In [6]:
DTE_result<-read.table(file="DTE_results.tsv", sep="\t", header=T)


cat("\nDTE_result\n")
cat(str(DTE_result))
cat("\n")

DTE_result
'data.frame':	71955 obs. of  11 variables:
 $ transcript_id : chr  "ENSMUST00000000001" "ENSMUST00000000010" "ENSMUST00000000028" "ENSMUST00000000033" ...
 $ gene_id       : chr  "ENSMUSG00000000001" "ENSMUSG00000020875" "ENSMUSG00000000028" "ENSMUSG00000048583" ...
 $ gene_name     : chr  "Gnai3" "Hoxb9" "Cdc45" "Igf2" ...
 $ baseMean      : num  7334.45 5.142 1268.765 0.387 33.847 ...
 $ log2FoldChange: num  0.16947 0.03455 -0.01901 -0.00109 0.77526 ...
 $ lfcSE         : num  0.0379 0.1313 0.0446 0.1268 0.2084 ...
 $ pvalue        : num  2.93e-06 1.68e-01 6.48e-01 9.24e-01 9.97e-06 ...
 $ padj          : num  0.000152 0.712289 0.999863 0.999863 0.000449 ...
 $ contrast      : chr  "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" ...
 $ minuslog10padj: num  3.82 1.47e-01 5.94e-05 5.94e-05 3.35 ...
 $ abslogfc      : num  0.16947 0.03455 0.01901 0.00109 0.77526 ...

In [46]:
normalized_counts_transcript_subset<-normalized_counts_transcript[which(row.names(normalized_counts_transcript)%in%max_shift_long_data$transcript_id),]

normalized_counts_transcript_subset$transcript_id<-row.names(normalized_counts_transcript_subset)

cat("normalized_counts_transcript_subset\n")
cat(str(normalized_counts_transcript_subset))
cat("\n")

DTE_result_subset<-DTE_result[which(DTE_result$transcript_id%in%max_shift_long_data$transcript_id),]

cat("DTE_result_subset\n")
cat(str(DTE_result_subset))
cat("\n")

normalized_counts_transcript_subset
'data.frame':	422 obs. of  31 variables:
 $ LM411_R1_t0  : num  0 9.85 2890.97 902.74 3574.86 ...
 $ LM411_R1_t1  : num  7.6 14.4 1807.8 952.9 3238.8 ...
 $ LM411_R1_t2  : num  4.05 15.19 2101.12 1084.48 2749.17 ...
 $ LM411_R1_t3  : num  10.1 18 2252.8 1401.8 2441.6 ...
 $ LM411_R1_t4  : num  33 0 2436 1616 2283 ...
 $ LM411_R2_t0  : num  0 9.12 2883.92 1073.8 3383.92 ...
 $ LM411_R2_t1  : num  0 16.5 2086.7 1002.6 3340.3 ...
 $ LM411_R2_t2  : num  7.76 11.21 1966.4 1116.39 2909.52 ...
 $ LM411_R2_t3  : num  14.69 7.91 2212.64 1289.39 2668.05 ...
 $ LM411_R2_t4  : num  13.56 7.75 2291.5 1661.97 2454.21 ...
 $ LM411_R3_t0  : num  4.23 7.62 2955.59 783.53 2921.75 ...
 $ LM411_R3_t1  : num  6.28 7.07 2215.74 966.88 3452.02 ...
 $ LM411_R3_t2  : num  4.89 18.57 1984.86 1027.13 2650.39 ...
 $ LM411_R3_t3  : num  9.49 17.93 2214.42 1390.87 2435.86 ...
 $ LM411_R3_t4  : num  11.72 6.31 2426.8 1812.66 2400.65 ...
 $ LM511_R1_t0  : num  0 3.22 2665.65 930.83 2899.97 ...
 $ LM511_R1_t1  : num  13.7 13.7 1794.4 877.7 2789.2 ...
 $ LM511_R1_t2  : num  0 15.2 1940.2 1446.6 2766.4 ...
 $ LM511_R1_t3  : num  0 20 2182 1719 2217 ...
 $ LM511_R1_t4  : num  10.2 13.6 2158 1989.6 2362.6 ...
 $ LM511_R2_t0  : num  0 3.04 3028.8 876.09 3600.69 ...
 $ LM511_R2_t1  : num  5.07 11.16 1854.81 1109.44 2920.64 ...
 $ LM511_R2_t2  : num  8.11 18.03 1990.25 1227.68 2744.7 ...
 $ LM511_R2_t3  : num  0 11.8 2572.6 1654.3 2476.2 ...
 $ LM511_R2_t4  : num  8.48 25.45 2093.63 1761.3 2285.95 ...
 $ LM511_R3_t0  : num  0 9.22 2885.39 994.57 3115.85 ...
 $ LM511_R3_t1  : num  0 25.8 2025.4 1073.8 3045.8 ...
 $ LM511_R3_t2  : num  9.98 13.31 2091.95 1346.57 2757.48 ...
 $ LM511_R3_t3  : num  0 18.1 2430.1 1617.9 2353.5 ...
 $ LM511_R3_t4  : num  0 26 2359 2167 2164 ...
 $ transcript_id: chr  "ENSMUST00000000707" "ENSMUST00000101257" "ENSMUST00000072334" "ENSMUST00000108797" ...

DTE_result_subset
'data.frame':	422 obs. of  11 variables:
 $ transcript_id : chr  "ENSMUST00000000707" "ENSMUST00000002469" "ENSMUST00000003152" "ENSMUST00000003461" ...
 $ gene_id       : chr  "ENSMUSG00000000693" "ENSMUSG00000002396" "ENSMUSG00000003068" "ENSMUSG00000020456" ...
 $ gene_name     : chr  "Loxl3" "Ocel1" "Stk11" "Ogdh" ...
 $ baseMean      : num  6.09 163.05 3073.49 4398 385.55 ...
 $ log2FoldChange: num  -0.0337 -0.3065 -0.0966 -0.0802 1.1196 ...
 $ lfcSE         : num  0.1323 0.1335 0.0337 0.0481 0.5267 ...
 $ pvalue        : num  0.04032 0.002113 0.002396 0.069792 0.000693 ...
 $ padj          : num  0.3349 0.0393 0.0433 0.4626 0.0162 ...
 $ contrast      : chr  "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" ...
 $ minuslog10padj: num  0.475 1.405 1.363 0.335 1.791 ...
 $ abslogfc      : num  0.0337 0.3065 0.0966 0.0802 1.1196 ...

## Gene expression

In [15]:
setwd("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/")

In [16]:
normalized_counts_genes<-read.table(file="nor_counts.tsv", sep="\t", header=T)


cat("\nnormalized_counts_genes\n")
cat(str(normalized_counts_genes))
cat("\n")

normalized_counts_genes
'data.frame':	14846 obs. of  30 variables:
 $ LM411_R1_t0: num  7030.9 75.7 0 20.9 1648 ...
 $ LM411_R1_t1: num  7194.1 816.2 0 47.4 827.8 ...
 $ LM411_R1_t2: num  6598.42 1916.53 3.93 59.86 973.47 ...
 $ LM411_R1_t3: num  6758.3 2177 24.9 71.4 937 ...
 $ LM411_R1_t4: num  7568.6 2330.8 263.3 56.6 996.6 ...
 $ LM411_R2_t0: num  6485.4 53.1 0 24.6 1662.2 ...
 $ LM411_R2_t1: num  7012.9 661.5 0 41.3 816.1 ...
 $ LM411_R2_t2: num  6565.92 1832.6 8.78 64.07 1009.33 ...
 $ LM411_R2_t3: num  7103.4 1946.6 44.2 65.8 938.8 ...
 $ LM411_R2_t4: num  7299.4 2234.8 315.6 65.3 906.1 ...
 $ LM411_R3_t0: num  6772.6 74.3 0 18.3 1604.3 ...
 $ LM411_R3_t1: num  7232.7 609.37 0.83 44.83 854.28 ...
 $ LM411_R3_t2: num  6660 1780 7 91 1053 ...
 $ LM411_R3_t3: num  7324 2061 67 100 1004 ...
 $ LM411_R3_t4: num  7502 2284 325 58 855 ...
 $ LM511_R1_t0: num  6406.46 68.9 0 8.44 1496.15 ...
 $ LM511_R1_t1: num  7667.6 848 0 86.5 1172.5 ...
 $ LM511_R1_t2: num  7627.92 1889.02 4.92 60.02 1140.3 ...
 $ LM511_R1_t3: num  8444.8 2048.1 18 85.1 1148.9 ...
 $ LM511_R1_t4: num  8387.5 2217.9 65 70.4 1438.4 ...
 $ LM511_R2_t0: num  6767.9 89.1 0 20.8 1657.8 ...
 $ LM511_R2_t1: num  7922 812 0 59 1124 ...
 $ LM511_R2_t2: num  8055.42 1794.51 3.61 61.38 1207.77 ...
 $ LM511_R2_t3: num  8612.81 1897.24 9.74 75.76 1124.49 ...
 $ LM511_R2_t4: num  7699.9 2296.5 99.2 79.2 1131.3 ...
 $ LM511_R3_t0: num  6602.1 82.1 0 12.8 1662.7 ...
 $ LM511_R3_t1: num  8147.88 729.68 3.04 69.83 1151.69 ...
 $ LM511_R3_t2: num  8266.19 1729.54 8.53 40.49 1186.06 ...
 $ LM511_R3_t3: num  9135.5 2037.4 19.7 90.5 1106.8 ...
 $ LM511_R3_t4: num  8268.9 2351.5 95.3 74.3 1175.7 ...

In [17]:
str(row.names(normalized_counts_genes))
cat("\n")

 chr [1:14846] "Gnai3" "Cdc45" "H19" "Scml2" "Narf" "Cav2" "Klf6" "Scmh1" ...

In [18]:
DGE_result<-read.table(file="DE_results.tsv", sep="\t", header=T)


cat("\nDGE_result\n")
cat(str(DGE_result))
cat("\n")

DGE_result
'data.frame':	14846 obs. of  9 variables:
 $ gene          : chr  "Inhba" "Lum" "Dlg2" "Tpbg" ...
 $ baseMean      : num  3031 1238 177 325 11827 ...
 $ log2FoldChange: num  2.45 2.4 3.11 2.87 2.59 ...
 $ lfcSE         : num  0.0821 0.1077 0.1401 0.1383 0.1273 ...
 $ pvalue        : num  4.95e-197 7.39e-112 1.59e-110 6.44e-99 3.37e-94 ...
 $ padj          : num  7.34e-193 5.48e-108 7.87e-107 2.39e-95 9.97e-91 ...
 $ contrast      : chr  "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" ...
 $ minuslog10padj: num  192.1 107.3 106.1 94.6 90 ...
 $ abslogfc      : num  2.45 2.4 3.11 2.87 2.59 ...

In [47]:
normalized_counts_genes_subset<-normalized_counts_genes[which(row.names(normalized_counts_genes)%in%max_shift_long_data$gene_name),]

normalized_counts_genes_subset$gene_name<-row.names(normalized_counts_genes_subset)

cat("normalized_counts_genes_subset\n")
cat(str(normalized_counts_genes_subset))
cat("\n")

DGE_result_subset<-DGE_result[which(DGE_result$gene%in%max_shift_long_data$gene_name),]

colnames(DGE_result_subset)[which(colnames(DGE_result_subset) == 'gene')]<-'gene_name'

cat("DGE_result_subset\n")
cat(str(DGE_result_subset))
cat("\n")

normalized_counts_genes_subset
'data.frame':	142 obs. of  31 variables:
 $ LM411_R1_t0: num  11.8 9030.3 5235.3 552.4 1364.7 ...
 $ LM411_R1_t1: num  26 6562 4680 481 363 ...
 $ LM411_R1_t2: num  19.6 6034.2 4598.5 536.8 380.8 ...
 $ LM411_R1_t3: num  27.1 6043.1 3615 388.4 445.8 ...
 $ LM411_R1_t4: num  31.1 6140.2 2666.3 422.6 382.2 ...
 $ LM411_R2_t0: num  10.8 8895 5466.4 588.1 1195 ...
 $ LM411_R2_t1: num  17.3 6895.8 5091.7 468.6 376.4 ...
 $ LM411_R2_t2: num  19.3 6350.9 4161.1 491.5 363.4 ...
 $ LM411_R2_t3: num  21.6 6092.3 3431.4 401.4 401.4 ...
 $ LM411_R2_t4: num  19 6184 2442 469 467 ...
 $ LM411_R3_t0: num  17.2 8701 4960.5 519 863.5 ...
 $ LM411_R3_t1: num  14.1 7138.1 5037.7 451.6 376.9 ...
 $ LM411_R3_t2: num  24 5983 4116 530 424 ...
 $ LM411_R3_t3: num  26.4 5969.6 3310.1 394.9 424.3 ...
 $ LM411_R3_t4: num  16.8 6388.1 2375.2 401.5 507.3 ...
 $ LM511_R1_t0: num  4.22 8721 5301.22 513.25 899.94 ...
 $ LM511_R1_t1: num  27.8 5996.5 3222.8 465.7 377.1 ...
 $ LM511_R1_t2: num  14.8 6193.4 3344.2 492.9 419.1 ...
 $ LM511_R1_t3: num  18.9 5935.3 2814 354.6 366.9 ...
 $ LM511_R1_t4: num  22.4 6361.5 2579.4 435 379.6 ...
 $ LM511_R2_t0: num  3.47 8790.39 5149.43 575.38 1187.8 ...
 $ LM511_R2_t1: num  16.9 6333.4 3291.6 442.5 384.6 ...
 $ LM511_R2_t2: num  26.2 6235.6 3058.2 406.2 413.4 ...
 $ LM511_R2_t3: num  10.8 6265.3 2521.7 359.3 375.6 ...
 $ LM511_R2_t4: num  33.3 5942.7 1989.6 440.1 452.1 ...
 $ LM511_R3_t0: num  11.5 8976.9 4962.5 592.7 998.1 ...
 $ LM511_R3_t1: num  27.3 6732 3569.4 505 368.4 ...
 $ LM511_R3_t2: num  22.4 6196.7 3163.9 482.7 406 ...
 $ LM511_R3_t3: num  16.7 6004.1 2274.5 389.6 336.5 ...
 $ LM511_R3_t4: num  24.1 6321.5 1807.1 418.8 393.7 ...
 $ gene_name  : chr  "Loxl3" "Dnajc5" "Gramd3" "Lmf1" ...

DGE_result_subset
'data.frame':	142 obs. of  9 variables:
 $ gene_name     : chr  "Dnajb5" "Shisa5" "Mtmr7" "Nrn1" ...
 $ baseMean      : num  1497 30264 256 211 4952 ...
 $ log2FoldChange: num  0.39 -0.663 0.727 1.553 0.26 ...
 $ lfcSE         : num  0.0441 0.0777 0.0872 0.1972 0.0328 ...
 $ pvalue        : num  1.55e-19 5.93e-19 4.69e-18 1.94e-17 4.61e-16 ...
 $ padj          : num  1.63e-17 5.39e-17 3.78e-16 1.45e-15 2.64e-14 ...
 $ contrast      : chr  "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" "treat_LM511_vs_LM411" ...
 $ minuslog10padj: num  16.8 16.3 15.4 14.8 13.6 ...
 $ abslogfc      : num  0.39 0.663 0.727 1.553 0.26 ...

tpm_counts_subset <- as.data.frame(fread("TPM_Counts_Subset.tsv", header = TRUE))
cat("Reloaded 'TPM_Counts_Subset.tsv' into 'tpm_counts_subset' (using fread)\n")

In [10]:
final_switch_summary

  Gene_Symbol Gene_ID            Max_Delta_pi Max_Shift_TimePoint
1 Dnah10      ENSMUSG00000038011 0.63738743   t0
2 Stard9      ENSMUSG00000033705 0.33267304   t3
3 Zfp287      ENSMUSG00000005267 0.26434146   t1
4 Gm1043      ENSMUSG00000117286 0.07869132   t1
5 Rer1        ENSMUSG00000029048 0.04824699   t4
6 Brd2        ENSMUSG00000024335 0.04595970   t4
7 Dnajc5      ENSMUSG00000000826 0.03557331   t4
  MET_ID_LM411       MET_Biotype_LM411       MET_ID_LM511
1 ENSMUST00000058440 protein_coding          ENSMUST00000196708
2 ENSMUST00000180041 protein_coding          ENSMUST00000154193
3 ENSMUST00000005399 protein_coding          ENSMUST00000149228
4 ENSMUST00000232332 protein_coding          ENSMUST00000213782
5 ENSMUST00000030914 protein_coding          ENSMUST00000149796
6 ENSMUST00000154232 nonsense_mediated_decay ENSMUST00000095347
7 ENSMUST00000116365 nonsense_mediated_decay ENSMUST00000072334
  MET_Biotype_LM511              ID_Switched Biotype_Switched
1 retained_intron                TRUE        TRUE
2 nonsense_mediated_decay        TRUE        TRUE
3 nonsense_mediated_decay        TRUE        TRUE
4 retained_intron                TRUE        TRUE
5 protein_coding_CDS_not_defined TRUE        TRUE
6 protein_coding                 TRUE        TRUE
7 protein_coding                 TRUE        TRUE

In [11]:
cat("max_shift_long_data\n")
str(max_shift_long_data)

max_shift_long_data
'data.frame':	878 obs. of  14 variables:
 $ transcript_id           : chr  "ENSMUST00000000707" "ENSMUST00000000707" "ENSMUST00000002469" "ENSMUST00000002469" ...
 $ gene_id                 : chr  "ENSMUSG00000000693" "ENSMUSG00000000693" "ENSMUSG00000002396" "ENSMUSG00000002396" ...
 $ gene_name               : chr  "Loxl3" "Loxl3" "Ocel1" "Ocel1" ...
 $ proportion              : num  0.715 0.306 0.326 0.261 0.667 ...
 $ treat                   : chr  "LM411" "LM511" "LM411" "LM511" ...
 $ time_point              : chr  "t4" "t4" "t4" "t4" ...
 $ raw_pvalue              : num  6.78e-04 6.78e-04 8.36e-05 8.36e-05 2.50e-04 ...
 $ adj_pvalue              : num  0.03673 0.03673 0.00821 0.00821 0.01802 ...
 $ Overall_Max_Delta_pi    : num  0.4091 0.4091 0.0726 0.0726 0.0425 ...
 $ Time_Point_of_Max_Shift : chr  "t4" "t4" "t4" "t4" ...
 $ Delta_pi                : num  -0.4091 -0.4091 -0.065 -0.065 -0.0425 ...
 $ transcript_biotype      : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ tag                     : chr  "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" "1 (assigned to previous version 8)" ...

In [30]:
cat("gtf_subset_rep\n")
str(gtf_subset_rep)

gtf_subset_rep
'data.frame':	11684 obs. of  27 variables:
 $ seqnames                : chr  "7" "7" "7" "7" ...
 $ source                  : chr  "ensembl_havana" "ensembl_havana" "ensembl_havana" "ensembl_havana" ...
 $ type                    : chr  "transcript" "exon" "CDS" "start_codon" ...
 $ start                   : int  5065244 5065244 5065287 5065287 5069402 5069402 5070209 5070209 5070543 5070543 ...
 $ end                     : int  5082932 5065335 5065335 5065289 5069537 5069537 5070253 5070253 5070646 5070646 ...
 $ score                   : logi  NA NA NA NA NA NA ...
 $ strand                  : chr  "+" "+" "+" "+" ...
 $ phase                   : int  NA NA 0 0 NA 2 NA 1 NA 1 ...
 $ gene_id                 : chr  "ENSMUSG00000030435" "ENSMUSG00000030435" "ENSMUSG00000030435" "ENSMUSG00000030435" ...
 $ gene_version            : int  18 18 18 18 18 18 18 18 18 18 ...
 $ gene_name               : chr  "U2af2" "U2af2" "U2af2" "U2af2" ...
 $ gene_source             : chr  "ensembl_havana" "ensembl_havana" "ensembl_havana" "ensembl_havana" ...
 $ gene_biotype            : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ transcript_id           : chr  "ENSMUST00000209099" "ENSMUST00000209099" "ENSMUST00000209099" "ENSMUST00000209099" ...
 $ transcript_version      : int  2 2 2 2 2 2 2 2 2 2 ...
 $ transcript_name         : chr  "U2af2-208" "U2af2-208" "U2af2-208" "U2af2-208" ...
 $ transcript_source       : chr  "ensembl_havana" "ensembl_havana" "ensembl_havana" "ensembl_havana" ...
 $ transcript_biotype      : chr  "protein_coding" "protein_coding" "protein_coding" "protein_coding" ...
 $ tag                     : chr  "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" "Ensembl_canonical" ...
 $ transcript_support_level: chr  "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" "1 (assigned to previous version 1)" ...
 $ exon_number             : int  NA 1 1 1 2 2 3 3 4 4 ...
 $ exon_id                 : chr  "" "ENSMUSE00001380707" "" "" ...
 $ exon_version            : int  NA 2 NA NA 2 NA 2 NA 2 NA ...
 $ protein_id              : chr  "" "" "ENSMUSP00000147013" "" ...
 $ protein_version         : int  NA NA 2 NA NA 2 NA 2 NA 2 ...
 $ ccds_id                 : chr  "CCDS57476" "CCDS57476" "CCDS57476" "CCDS57476" ...
 $ COORD                   : int  439 439 439 439 439 439 439 439 439 439 ...

## Create graph path

In [23]:
if(file.exists("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs/")){


}else{

    dir.create("/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs/")
}

    path_graphs<-"/group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs/"

setwd(path_graphs)

NULL

# All plots

# NOTE: This script assumes 'ggplot2', 'dplyr', 'scales', 'tidyr', 'cowplot', 
# 'ggtranscript', 'shorten_gaps', and 'to_intron' are loaded/available in the environment.

# --- 1. DEFINE HELPER FUNCTION (To create the multi-line Y-axis label)
create_transcript_label <- function(id, biotype, tag, ccds) {
    # FIX for nchar() error: Ensure 'id' is a character vector before substring operations
    id <- as.character(id)
    
    # FIX for argument is of length zero: Safely handle NULL or length-zero inputs.
    # A robust check: if it's NULL, length zero, or NA, use "". Otherwise, use the value.
    tag <- if (is.null(tag) || length(tag) == 0 || is.na(tag)) "" else as.character(tag)
    ccds <- if (is.null(ccds) || length(ccds) == 0 || is.na(ccds)) "" else as.character(ccds)
    
    # Start with the required elements
    # Using the last 4 characters of the ID to keep the label manageable on the plot grid
    short_id <- substr(id, nchar(id) - 3, nchar(id))
    parts <- c(paste(short_id, biotype, sep = "\n"))
    
    # Add optional elements only if they are not empty (NA check is handled above)
    if (tag != "") {
        parts <- c(parts, tag)
    }
    # Append ccds_id 
    if (ccds != "") {
        parts <- c(parts, ccds) 
    }
    
    # Collapse the parts with a newline separator
    return(paste(parts, collapse = "\n"))
}


# --- Prerequisites (Data Frames loaded from TSV files): ---
# max_shift_long_data: Full long-format data for all transcripts at their max shift time point (includes Time_Point_of_Max_Shift column)
# tpm_counts_subset: Raw TPM counts data (LONG format: gene_id, gene_name, transcript_id, sample, TPM, treat, batch, time_point)
# gtf_subset_rep: Cleaned GTF data frame (from user's 'gtf_subset_rep')

# --- 1. Define Universal Plotting Constants (Based on User Template) ---

breaks.Rank <- (seq(0, 1, by = 0.25))
labels.Rank <- as.character(breaks.Rank)
# 0.176 mm corresponds to 0.5 pt stroke (0.5 * 0.352778)
AXIS_STROKE_MM <- 0.176 
# 2.11 mm corresponds to 6 pt font size (6 / ggplot2::.pt)
LABEL_FONT_SIZE_MM <- 6 / ggplot2::.pt

# Placeholder for path_graphs (set to 'Graphs' if not defined externally)
if (!exists("path_graphs")) {
    path_graphs <- "Graphs"
}

# --- 2. Setup Output Folder ---

# Identify all unique genes in the data
all_dtu_genes <- unique(max_shift_long_data$gene_name)

# --- NEW ROBUST FILTER: Remove NA values and empty strings from the gene list ---
# This prevents the 'for' loop from crashing on records without a valid gene name.
all_dtu_genes <- all_dtu_genes[!is.na(all_dtu_genes) & all_dtu_genes != ""]
# ----------------------------------------------------------------------------

# Define the output directory
output_dir <- path_graphs

# Create the directory if it doesn't exist
if (!dir.exists(output_dir)) {
    dir.create(output_dir)
    cat(paste0("Created directory: ", output_dir, "\n"))
}

# --- 3. Iterate, Plot, and Save Combined Figures ---

# --- START GLOBAL PRE-FILTER: CANONICAL CHROMOSOMES ---
# 1. Ensure the chromosome column is named 'seqnames' in the global object for filtering
if ('seqid' %in% colnames(gtf_subset_rep)) {
    colnames(gtf_subset_rep)[which(colnames(gtf_subset_rep) == 'seqid')]<-'seqnames'
}
gtf_subset_rep$seqnames <- as.character(gtf_subset_rep$seqnames)

# 2. Filter out non-canonical chromosomes (Only keeping autosomes, X, Y, M, and MT)
initial_unique_seqnames <- unique(gtf_subset_rep$seqnames)

# Define canonical chromosome set (Ensembl style: numbers, X, Y, M/MT)
canonical_chromosomes <- c(as.character(1:22), "X", "Y", "M", "MT")

gtf_subset_rep <- gtf_subset_rep %>%
    dplyr::filter(seqnames %in% canonical_chromosomes) # Filter for strict canonical names

final_unique_seqnames <- unique(gtf_subset_rep$seqnames)

cat(paste0("Pre-filtering GTF data: Filtered to only canonical seqnames (1-22, X, Y, M, MT).\n"))
cat(paste0("Initial Seqnames Count: ", length(initial_unique_seqnames), ". Final Seqnames Count: ", length(final_unique_seqnames), ".\n"))
# --- END GLOBAL PRE-FILTER ---

cat("\nStarting iterative combined plot generation (Proportions + TPM Violin + Structure) and saving as SVG files to the 'Graphs' folder...\n")
plot_count <- 0

for (gene in all_dtu_genes) {
    
    # --- GENE EXCLUSION MECHANISM (For known fusion/complex genes) ---
    # If a previous run crashed on a gene, add its name here to skip it next time.
    GENES_TO_EXCLUDE <- c('Lcorl;Gm3414','Nupl1','Gramd3') # <--- Add gene names here if the script crashes (e.g., c("KNOWN_FUSION_GENE"))
    
    if (gene %in% GENES_TO_EXCLUDE) {
        cat(paste0("Skipping Gene: ", gene, " (Manually excluded due to complex locus/fusion annotation).\n"))
        next 
    }
    # --- END EXCLUSION MECHANISM ---
    
    # --- Log current gene for debugging ---
    cat(paste0("Processing Gene: ", gene, "...\n"))
    
    # --- Data Preparation for Current Gene (Proportion Plot) ---
    gene_data <- max_shift_long_data %>% 
        # Filter data for the current gene in the loop
        filter(gene_name == gene) %>%
        # Ensure 'treat' is properly ordered for the bar plot
        mutate(treat = factor(treat, levels = c("LM411", "LM511")))
    
    # Generate Full Transcript Labels for display on the bar plot and for TPM plot faceting
    gene_data_labeled <- gene_data %>%
        mutate(
            # Convert to character explicitly
            transcript_id = as.character(transcript_id),
            # Combine the full ID and proportion into the final label
            # This 'display_label' is treatment-specific!
            display_label = paste0(transcript_id, "\n(prop. = ", round(proportion, 2), ")")
        )

    # Extract overall metrics for title
    max_delta <- unique(gene_data_labeled$Overall_Max_Delta_pi)
    adj_pvalue <- unique(gene_data_labeled$adj_pvalue)[1]
    
    # Define the vertical order for alignment (reverse alphabetical order of IDs)
    depicted_order <- gene_data_labeled %>%
        dplyr::select(transcript_id, display_label) %>%
        distinct() %>%
        arrange(desc(transcript_id))
    
    # Set the desired order for the display_label factor
    display_label_order <- depicted_order %>% pull(display_label)
    
    gene_data_labeled$display_label <- factor(gene_data_labeled$display_label, 
                                             levels = display_label_order, 
                                             ordered = TRUE)
    
    
    # --- Plot 1: Proportion Bar Plot (p) ---
    p <- ggplot(data = gene_data_labeled,
                aes(x = treat, y = proportion)) +
        
        geom_bar(stat = "identity", fill = "lightgray", colour = 'black') +
        
        geom_text(aes(label = display_label),
                  position = position_stack(vjust = 0.5),
                  size = LABEL_FONT_SIZE_MM,
                  color = "black",
                  family = "sans") +
        
        scale_y_continuous(name = paste("DRIMseq modelled proportion", sep = " "),
                           breaks = breaks.Rank,
                           labels = labels.Rank) + 
        
        labs(
            title = paste(gene, " (DTU: $\\Delta\\pi$=", round(max_delta, 3), ", Adj P=", round(adj_pvalue, 3), ")"),
            x = "Treatment Group"
        ) +
        theme_classic() +
        
        # Axis and Theme Settings (Matching Template)
        theme(title = element_text(size = 8, color = "black", family = "sans"),
              axis.title.y = element_text(size = 8, color = "black", family = "sans"),
              axis.title.x = element_blank(), # Remove X-title
              axis.text.y = element_text(angle = 0, size = 6, color = "black", family = "sans"),
              axis.text.x = element_text(angle = 0, size = 6, color = "black", family = "sans"),
              axis.line.x = element_line(size = AXIS_STROKE_MM),
              axis.ticks.x = element_line(size = AXIS_STROKE_MM),
              axis.ticks.y = element_line(size = AXIS_STROKE_MM),
              axis.line.y = element_line(size = AXIS_STROKE_MM),
              legend.position = "none") # No legend on this plot
              
    
    # --- Data Preparation for Plot 2 (TPM Violin Plot) ---
    
    # 1. Robust Extraction of the Max Shift Time Point
    
    # Use the correct column name from user's data structure
    time_point_column <- "Time_Point_of_Max_Shift" 
    
    # Check if the required column exists in the DTU data
    if (!time_point_column %in% colnames(gene_data)) {
        cat(paste0("Skipping Gene: ", gene, ". CRITICAL ERROR: Column '", time_point_column, "' is missing from 'max_shift_long_data'. Please check your input data structure.\n"))
        next
    }
    
    # Extract the unique max shift time point(s) and filter out NA/empty strings
    temp_tp_vec <- unique(gene_data[[time_point_column]])
    valid_tp <- temp_tp_vec[!is.na(temp_tp_vec) & temp_tp_vec != ""]
    
    if (length(valid_tp) == 0) {
        cat(paste0("Skipping Gene: ", gene, ". No valid '", time_point_column, "' found. (Are these genes truly DTU significant?)\n"))
        next 
    }
    
    # Take the first valid time point found
    max_shift_tp <- as.character(valid_tp[1])
    
    
    # 2. Filter the TPM data (already in LONG format)
    tpm_long <- tpm_counts_subset %>%
        # Filter for the current gene
        dplyr::filter(gene_name == gene) %>%
        
        # Ensure the time_point column is character for consistent comparison
        dplyr::mutate(time_point = as.character(time_point)) %>% 
        
        # 3. CRITICAL STEP: Filter to the Max Shift Time Point
        dplyr::filter(time_point == max_shift_tp) %>%
        
        # *** FIX FOR DUPLICATE VIOLINS: Ensure each sample/transcript record is unique ***
        # This removes duplicates that can arise from merging/melting operations.
        dplyr::distinct(transcript_id, sample, .keep_all = TRUE) %>% 
        
        # 4. Filter for only the transcripts that were part of the DTU analysis (gene_data_labeled)
        dplyr::filter(transcript_id %in% unique(gene_data_labeled$transcript_id)) 

    # 5. Ensure 'treat' is properly factored, and factor the transcript_id for faceting order.
    tpm_long$treat <- factor(tpm_long$treat, levels = c("LM411", "LM511"))

    # *** FIX: Extract the unique transcript ID order from the proportion plot labels ***
    # This maintains the order from the proportion plot while ensuring faceting is unique.
    # It removes the proportion part (\n...) from the 'display_label' string.
    # *** CRITICAL FIX: Use unique() to prevent duplicated factor levels. ***
    transcript_id_order_from_prop <- unique(gsub("\n.*", "", display_label_order)) 

    tpm_long$transcript_id <- factor(tpm_long$transcript_id, 
                                     levels = transcript_id_order_from_prop, 
                                     ordered = TRUE)

    # --- Plot 2: TPM Violin Plot (p_tpm) ---
    p_tpm <- ggplot(data = tpm_long,
                  aes(x = treat, y = log10(TPM + 1), fill = treat)) +
        
        # Violin plot for distribution
        geom_violin(trim = TRUE, alpha = 0.4, scale = "width", color = "gray50") + # CHANGED trim = FALSE to trim = TRUE
        
        # Individual jittered points
        geom_jitter(width = 0.15, size = 1.5, alpha = 0.7, color = "black") +
        
        # Facet by transcript ID (now unique and correctly ordered)
        facet_wrap(~ transcript_id, 
                   nrow = 1, 
                   # Removed 'scales = "free_y"' to force fixed (same) y-scale across all facets for this gene
                   strip.position = "top") + 
        
        scale_fill_manual(values = c("LM411" = "#1f78b4", "LM511" = "#e31a1c")) +
        
        labs(
            y = expression(log[10](TPM + 1)),
            x = paste("Treatment Group at", max_shift_tp)
        ) +
        theme_classic() +
        
        # Axis and Theme Settings
        theme(title = element_blank(),
              axis.title.y = element_text(size = 8, color = "black", family = "sans"),
              axis.title.x = element_text(size = 8, color = "black", family = "sans"),
              axis.text.y = element_text(angle = 0, size = 6, color = "black", family = "sans"),
              # --- START CUSTOMIZATION FOR REDUNDANCY/READABILITY ---
              axis.text.x = element_blank(), # Remove X-axis labels
              axis.line.x = element_line(size = AXIS_STROKE_MM),
              axis.ticks.x = element_blank(), # Remove X-axis ticks
              axis.ticks.y = element_line(size = AXIS_STROKE_MM),
              axis.line.y = element_line(size = AXIS_STROKE_MM),
              legend.position = "bottom", # Add legend back
              # Styling for the facet strips
              strip.text.x.top = element_text(angle = 0, size = 6, family = "sans", margin = margin(t = 5, b = 5, unit = "pt")), # Horizontal facet labels
              strip.background = element_rect(fill = "gray95", color = "gray50")
              # --- END CUSTOMIZATION ---
              )
              
    # --- Data Preparation for Plot 3 (Structure) ---
    
    # Filter the GTF annotation for the current gene
    REP_ggtranscript <- gtf_subset_rep %>% 
        dplyr::filter(gene_name == gene) %>%
        # *** FIX: Drop factor levels from the filtered subset ***
        droplevels()

    # 1. Ensure the chromosome column is named 'seqnames' 
    if ('seqid' %in% colnames(REP_ggtranscript)) {
        colnames(REP_ggtranscript)[which(colnames(REP_ggtranscript) == 'seqid')]<-'seqnames'
    }
    REP_ggtranscript$seqnames <- as.character(REP_ggtranscript$seqnames)
    
    # --- RE-INTRODUCED PER-GENE SAFEGUARD FILTER (Ensures single chromosome) ---
    unique_seqnames_gene <- unique(REP_ggtranscript$seqnames)
    if (length(unique_seqnames_gene) > 1) {
        canonical_seqname_gene <- REP_ggtranscript %>%
            dplyr::group_by(seqnames) %>%
            dplyr::summarise(n = n(), .groups = 'drop') %>%
            dplyr::arrange(desc(n)) %>%
            dplyr::slice_head(n = 1) %>% 
            dplyr::pull(seqnames)
            
        REP_ggtranscript <- REP_ggtranscript %>% dplyr::filter(seqnames == canonical_seqname_gene)
        REP_ggtranscript$seqnames <- canonical_seqname_gene 
        
        cat(paste0("Warning: Gene ", gene, " was filtered and seqnames coerced to single value: ", canonical_seqname_gene, ".\n"))
    }
    # --- END RE-INTRODUCED PER-GENE SAFEGUARD ---
    
    # --- FINAL CRITICAL CHECK BEFORE PLOTTING ---
    if(length(unique(REP_ggtranscript$seqnames)) > 1) {
        cat(paste0("CRITICAL FAILURE: Gene ", gene, " is still annotated on multiple seqnames (", 
                   paste(unique(REP_ggtranscript$seqnames), collapse=", "), "). Skipping plot.\n"))
        next # Skip to the next gene in the 'for' loop
    }
    # --- END CRITICAL CHECK ---
    
    
    # Pre-calculate the multi-line Y-axis label
    REP_ggtranscript <- REP_ggtranscript %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            # Using ccds_id from the GTF annotation
            transcript_label = create_transcript_label(
                transcript_id, 
                transcript_biotype, 
                tag, 
                ccds_id
            )
        ) %>%
        dplyr::ungroup()
    
    # FIX 2: Create a temporary data frame to pull transcript labels in the desired 'depicted_order'
    # Use the same order as defined for the proportion/TPM plots
    label_lookup <- REP_ggtranscript %>% 
        dplyr::select(transcript_id, transcript_label) %>%
        dplyr::distinct() %>%
        # Join with the pre-defined order, then arrange
        dplyr::left_join(depicted_order, by = "transcript_id") %>%
        # The join can create NA in display_label if the GTF had extra transcripts not in max_shift_long_data
        # We need to filter only for those present in the DTU results
        dplyr::filter(!is.na(display_label)) %>% 
        dplyr::arrange(display_label) %>%
        dplyr::pull(transcript_label)
        
    # *** FIX: Ensure factor levels are unique by adding unique() ***
    label_levels <- unique(as.character(label_lookup)) 
    
    REP_ggtranscript$transcript_label <- factor(REP_ggtranscript$transcript_label,
                                                    levels = label_levels,
                                                    ordered = TRUE)
    
    # 3. TRANSCRIPT PLOTTING
    # Extract exons (using the data with the FACTORED 'transcript_label' column)
    REP_exons <- REP_ggtranscript %>% dplyr::filter(type == "exon")

    # --- SECOND CRITICAL CHECK: ON REP_EXONS (The actual crashing object) ---
    if(length(unique(REP_exons$seqnames)) > 1) {
        cat(paste0("CRITICAL FAILURE (Exons): Gene ", gene, " is still annotated on multiple seqnames (", 
                   paste(unique(REP_exons$seqnames), collapse=", "), ") in the REP_exons object. Skipping plot.\n"))
        next # Skip to the next gene in the 'for' loop
    }
    # --- END SECOND CRITICAL CHECK ---
    
    # NOTE: The following lines require the 'ggtranscript' package functions to be loaded
    REP_exons_rescaled <- shorten_gaps(
        REP_exons, 
        to_intron(REP_exons, "transcript_label"), 
        group_var = "transcript_label" 
    )
    
    transcript_plot <- REP_exons_rescaled %>%
        dplyr::filter(type == "exon") %>%
        ggplot(aes(
            xstart = start,
            xend = end,
            y = transcript_label # Map the factored label directly
        )) +
        # Use scale_y_discrete() to respect the factor order
        scale_y_discrete() + 
        geom_range(height = 0.25,
            fill="steelblue"
        ) +
        geom_intron(
            data = REP_exons_rescaled %>% dplyr::filter(type == "intron"),
            aes(strand=strand),
            arrow = grid::arrow(ends = "last", length = grid::unit(0.25, "cm")),
            arrow.min.intron.length = 200
        )
    
    # 4. THEME APPLICATION
    transcript_plot <- transcript_plot +
        theme_classic() +
        theme(
            axis.title.y=element_blank(),
            axis.title.x=element_blank(),
            axis.text.y=element_text(angle=0,size=8, color="black", family="sans"),
            axis.text.x=element_text(angle=0,size=8, color="black", family="sans"),
            axis.line.x = element_line(size = 0.4),
            axis.ticks = element_line(size = 0.4),
            axis.line.y = element_line(size = 0.4)
        ) +
        theme(
            legend.title = element_blank(),
            legend.text = element_text(size=6),
            legend.key.size = unit(0.25, 'cm'),
            legend.key.height = unit(0.25, 'cm'),
            legend.key.width = unit(0.25, 'cm'),
            legend.position="bottom"
        )
    
    
    # --- Combine Plots Side-by-Side ---
    # Increased width for the TPM plot for horizontal faceting
    combined_plot <- plot_grid(p, p_tpm, transcript_plot, nrow = 1, 
                               rel_widths = c(1.5, 4.5, 3.5), # Increased TPM width
                               align = 'h', axis = 'l')

    
    # --- Save Combined Figure ---
    
    filename <- file.path(output_dir, paste0(gene, "_DTU_Combined_Plot.svg"))
    
    ggsave(filename, 
           plot = combined_plot, 
           device = "svg", 
           width = 18, # *** Increased width for horizontal layout ***
           height = 6, 
           units = "in")
    
    plot_count <- plot_count + 1
}

cat(paste0("\nSuccessfully finished processing ", plot_count, " individual DTU genes and saved combined figures to the '", output_dir, "' folder.\n"))

# Strategy different 3'UTR

In [36]:
# --- Script to filter the DTU list down to only 3' UTR switch genes ---
# A 3' UTR switch is defined as a gene where:
# 1. The Most Expressed Transcript (MET) ID changes between conditions.
# 2. The Biotype of the METs remains the same.
# 3. The 3' UTR length of the two METs is different.
# 4. The Coding Sequence (CDS) of the two METs is identical.

# Prerequisites: 
# max_shift_long_data (reloaded from Max_Shift_Annotated_Transcripts.tsv)
# gtf_subset_rep (The annotated GTF data frame provided in the context)

# Use the final annotated data frame
if (!exists("max_shift_long_data")) {
    stop("Error: 'max_shift_long_data' data frame (reloaded from Max_Shift_Annotated_Transcripts.tsv) is required but not found.")
}
if (!exists("gtf_subset_rep")) {
    stop("Error: 'gtf_subset_rep' (GTF annotations) data frame is required but not found.")
}

# Alias the data frame to the local variable 'df_annotated' for cleaner code
df_annotated <- max_shift_long_data

# --- A. Calculate 3' UTR Lengths from GTF ---
# Sums the length of all segments marked as 'three_prime_utr' for each transcript.
utr3_lengths <- gtf_subset_rep %>%
    # Filter for the specific feature type
    dplyr::filter(type == "three_prime_utr") %>%
    
    # Calculate the length of each UTR segment: (end - start + 1)
    dplyr::mutate(utr3_segment_length = end - start + 1) %>%
    
    # Group by transcript and sum segment lengths for total 3' UTR length
    dplyr::group_by(transcript_id) %>%
    dplyr::summarise(
        UTR3_Length = sum(utr3_segment_length, na.rm = TRUE),
        .groups = 'drop'
    )

# --- B. Calculate CDS Signature from GTF ---
# Creates a unique identifier for the CDS (coding sequence) of each transcript
# by concatenating the sorted start/end coordinates of all CDS segments.
cds_signatures <- gtf_subset_rep %>%
    dplyr::filter(type == "CDS") %>%
    
    # Sort coordinates to ensure a consistent signature regardless of row order
    dplyr::arrange(transcript_id, start) %>%
    
    # Concatenate all start and end points into a single, unique string per transcript
    dplyr::group_by(transcript_id) %>%
    dplyr::summarise(
        CDS_Signature = paste(start, end, collapse = "_"),
        .groups = 'drop'
    )


# --- 1. Identify the Most Expressed Transcript (MET), Biotype, UTR Length, and CDS Signature per Condition ---
MET_by_condition <- df_annotated %>%
    
    # Group by gene, time point, and treatment
    dplyr::group_by(gene_id, gene_name, Time_Point_of_Max_Shift, treat) %>%
    
    # Find the row with the maximum proportion (the MET)
    dplyr::slice_max(order_by = proportion, n = 1, with_ties = FALSE) %>% 
    dplyr::ungroup() %>%
    
    # Select the key MET information
    dplyr::select(
        gene_id, gene_name, Time_Point_of_Max_Shift, treat,
        MET_ID = transcript_id,
        MET_Biotype = transcript_biotype
    ) %>%
    
    # Join with the pre-calculated 3' UTR lengths
    dplyr::left_join(utr3_lengths, by = c("MET_ID" = "transcript_id")) %>%
    dplyr::mutate(UTR3_Length = tidyr::replace_na(UTR3_Length, 0)) %>%

    # NEW: Join with the pre-calculated CDS signature
    dplyr::left_join(cds_signatures, by = c("MET_ID" = "transcript_id")) %>%
    # Assign a unique placeholder for non-coding transcripts (no CDS feature)
    dplyr::mutate(CDS_Signature = tidyr::replace_na(CDS_Signature, "NON_CODING_MET"))


# --- 2. Pivot to Compare METs Side-by-Side and Filter ---
UTR3_Switch_Summary_DF <- MET_by_condition %>%
    
    # Pivot to align LM411 and LM511 METs side-by-side
    tidyr::pivot_wider(
        id_cols = c(gene_id, gene_name, Time_Point_of_Max_Shift),
        names_from = treat,
        values_from = c(MET_ID, MET_Biotype, UTR3_Length, CDS_Signature)
    ) %>%
    
    # Check for switches
    dplyr::mutate(
        # 1. MET ID must be different (Required: TRUE)
        ID_Switched = (MET_ID_LM411 != MET_ID_LM511),
        
        # 2. MET biotype must be the same (Required: FALSE)
        Biotype_Switched = (MET_Biotype_LM411 != MET_Biotype_LM511),
        
        # 3. 3' UTR length must be different (Required: TRUE)
        UTR3_Switched = (UTR3_Length_LM411 != UTR3_Length_LM511),
        
        # 4. CDS signature must be the same (Required: TRUE)
        CDS_Same = (CDS_Signature_LM411 == CDS_Signature_LM511)
    ) %>%
    
    # --- Filter to keep ONLY genes meeting the four criteria ---
    dplyr::filter(
        ID_Switched == TRUE,
        Biotype_Switched == FALSE,
        UTR3_Switched == TRUE,
        CDS_Same == TRUE
    ) %>%
    
    # Join the overall Max Delta Pi metric back for final prioritization
    dplyr::left_join(
        df_annotated %>% 
            dplyr::select(gene_id, Overall_Max_Delta_pi, adj_pvalue) %>% 
            dplyr::distinct(), 
        by = "gene_id"
    ) %>%
    
    # --- 3. Final Ordering and Selection ---
    
    # Sort by the magnitude of the shift
    dplyr::arrange(dplyr::desc(Overall_Max_Delta_pi)) %>%
    
    # Reorder and rename columns for a clean presentation
    dplyr::select(
        Gene_Symbol = gene_name,
        Gene_ID = gene_id,
        Max_Delta_pi = Overall_Max_Delta_pi,
        Adj_P_Value = adj_pvalue,
        Max_Shift_TimePoint = Time_Point_of_Max_Shift,
        
        # Side-by-side comparison columns:
        MET_ID_LM411,
        UTR3_Length_LM411,
        MET_ID_LM511,
        UTR3_Length_LM511,
        MET_Biotype_Common = MET_Biotype_LM411,
        
        # Confirmation flags
        ID_Switched,
        Biotype_Switched,
        UTR3_Switched,
        CDS_Same
    ) %>%
    
    # 4. Extract the gene symbols into a dedicated vector for plotting
    as.data.frame()

# Export the final list of gene names to be used by the visualization script
functional_switch_genes <- UTR3_Switch_Summary_DF$Gene_Symbol

cat("\n--- 3' UTR Alternative Polyadenylation (APA) Switch Filtering Complete ---\n")
cat(paste0("Identified ", length(functional_switch_genes), " genes where the MET ID and 3' UTR length switched, with identical CDS and biotype.\n"))

# Print the top 5 3' UTR switches for review
cat("\nTop 5 3' UTR/APA Switch Genes (by Max Delta Pi):\n")
print(UTR3_Switch_Summary_DF[1:min(5, nrow(UTR3_Switch_Summary_DF)), ])

# The object 'functional_switch_genes' is now available for the visualization script.

--- 3' UTR Alternative Polyadenylation (APA) Switch Filtering Complete ---
Identified 4 genes where the MET ID and 3' UTR length switched, with identical CDS and biotype.

Top 5 3' UTR/APA Switch Genes (by Max Delta Pi):
  Gene_Symbol            Gene_ID Max_Delta_pi  Adj_P_Value Max_Shift_TimePoint
1     Rasgrp2 ENSMUSG00000032946   0.25396215 0.0023356292                  t4
2         Sla ENSMUSG00000022372   0.18116600 0.0000460725                  t0
3     St6gal1 ENSMUSG00000022885   0.09610355 0.0087323353                  t3
4     Tnfaip3 ENSMUSG00000019850   0.06327018 0.0180205806                  t3
        MET_ID_LM411 UTR3_Length_LM411       MET_ID_LM511 UTR3_Length_LM511
1 ENSMUST00000113476               221 ENSMUST00000167240               226
2 ENSMUST00000164163              1723 ENSMUST00000100572              1678
3 ENSMUST00000178797              2480 ENSMUST00000023601              2478
4 ENSMUST00000019997              1821 ENSMUST00000105527              1818
  MET_Biotype_Common ID_Switched Biotype_Switched UTR3_Switched CDS_Same
1     protein_coding        TRUE            FALSE          TRUE     TRUE
2     protein_coding        TRUE            FALSE          TRUE     TRUE
3     protein_coding        TRUE            FALSE          TRUE     TRUE
4     protein_coding        TRUE            FALSE          TRUE     TRUE

In [127]:
# --- SAVE THE FINAL FILTERED SUMMARY TO TSV ---
write.table(
    UTR3_Switch_Summary_DF,
    file = "UTR3_APA_Switch_Summary.tsv", # The target file name
    sep = "\t", # Tab-separated format
    row.names = FALSE,
    quote = FALSE,
    na = "" # Write empty strings for NA values
)

cat("\n--- 3' UTR Alternative Polyadenylation (APA) Switch Filtering Complete ---\n")
cat("Data frame 'UTR3_Switch_Summary_DF' has been saved to 'UTR3_APA_Switch_Summary.tsv'.\n")

# Print the top 5 3' UTR switches for review
cat("\nTop 5 3' UTR/APA Switch Genes (by Max Delta Pi):\n")
print(UTR3_Switch_Summary_DF[1:min(5, nrow(UTR3_Switch_Summary_DF)), ])

--- 3' UTR Alternative Polyadenylation (APA) Switch Filtering Complete ---
Data frame 'UTR3_Switch_Summary_DF' has been saved to 'UTR3_APA_Switch_Summary.tsv'.

Top 5 3' UTR/APA Switch Genes (by Max Delta Pi):
  Gene_Symbol            Gene_ID Max_Delta_pi  Adj_P_Value Max_Shift_TimePoint
1     Rasgrp2 ENSMUSG00000032946   0.25396215 0.0023356292                  t4
2         Sla ENSMUSG00000022372   0.18116600 0.0000460725                  t0
3     St6gal1 ENSMUSG00000022885   0.09610355 0.0087323353                  t3
4     Tnfaip3 ENSMUSG00000019850   0.06327018 0.0180205806                  t3
        MET_ID_LM411 UTR3_Length_LM411       MET_ID_LM511 UTR3_Length_LM511
1 ENSMUST00000113476               221 ENSMUST00000167240               226
2 ENSMUST00000164163              1723 ENSMUST00000100572              1678
3 ENSMUST00000178797              2480 ENSMUST00000023601              2478
4 ENSMUST00000019997              1821 ENSMUST00000105527              1818
  MET_Biotype_Common ID_Switched Biotype_Switched UTR3_Switched CDS_Same
1     protein_coding        TRUE            FALSE          TRUE     TRUE
2     protein_coding        TRUE            FALSE          TRUE     TRUE
3     protein_coding        TRUE            FALSE          TRUE     TRUE
4     protein_coding        TRUE            FALSE          TRUE     TRUE

# Strategy different 5'UTR

In [128]:
# --- SCRIPT TO EXECUTE 5' UTR (ATSS) SWITCH FILTERING AND SAVE RESULTS ---
# This script runs the complex four-part filter for Alternative Transcription Start Site (ATSS)
# or 5' UTR splicing changes (different MET ID, same biotype,
# different 5' UTR length, same CDS signature) and saves the final data table.

# Dependencies (assumed to be loaded): dplyr, tidyr, data.table

# Prerequisites: 
# max_shift_long_data (reloaded from Max_Shift_Annotated_Transcripts.tsv)
# gtf_subset_rep (The annotated GTF data frame provided in the context)

# Use the final annotated data frame
if (!exists("max_shift_long_data")) {
    stop("Error: 'max_shift_long_data' data frame (reloaded from Max_Shift_Annotated_Transcripts.tsv) is required but not found.")
}
if (!exists("gtf_subset_rep")) {
    stop("Error: 'gtf_subset_rep' (GTF annotations) data frame is required but not found.")
}

# Alias the data frame to the local variable 'df_annotated' for cleaner code
df_annotated <- max_shift_long_data

# --- A. Calculate 5' UTR Lengths from GTF ---
# Sums the length of all segments marked as 'five_prime_utr' for each transcript.
utr5_lengths <- gtf_subset_rep %>%
    # Filter for the specific feature type
    dplyr::filter(type == "five_prime_utr") %>%
    
    # Calculate the length of each UTR segment: (end - start + 1)
    dplyr::mutate(utr5_segment_length = end - start + 1) %>%
    
    # Group by transcript and sum segment lengths for total 5' UTR length
    dplyr::group_by(transcript_id) %>%
    dplyr::summarise(
        UTR5_Length = sum(utr5_segment_length, na.rm = TRUE),
        .groups = 'drop'
    )

# --- B. Calculate CDS Signature from GTF ---
# Creates a unique identifier for the CDS (coding sequence) of each transcript
# by concatenating the sorted start/end coordinates of all CDS segments.
cds_signatures <- gtf_subset_rep %>%
    dplyr::filter(type == "CDS") %>%
    
    # Sort coordinates to ensure a consistent signature regardless of row order
    dplyr::arrange(transcript_id, start) %>%
    
    # Concatenate all start and end points into a single, unique string per transcript
    dplyr::group_by(transcript_id) %>%
    dplyr::summarise(
        CDS_Signature = paste(start, end, collapse = "_"),
        .groups = 'drop'
    )


# --- 1. Identify the Most Expressed Transcript (MET), Biotype, UTR Length, and CDS Signature per Condition ---
MET_by_condition <- df_annotated %>%
    
    # Group by gene, time point, and treatment
    dplyr::group_by(gene_id, gene_name, Time_Point_of_Max_Shift, treat) %>%
    
    # Find the row with the maximum proportion (the MET)
    dplyr::slice_max(order_by = proportion, n = 1, with_ties = FALSE) %>% 
    dplyr::ungroup() %>%
    
    # Select the key MET information
    dplyr::select(
        gene_id, gene_name, Time_Point_of_Max_Shift, treat,
        MET_ID = transcript_id,
        MET_Biotype = transcript_biotype
    ) %>%
    
    # Join with the pre-calculated 5' UTR lengths
    dplyr::left_join(utr5_lengths, by = c("MET_ID" = "transcript_id")) %>%
    dplyr::mutate(UTR5_Length = tidyr::replace_na(UTR5_Length, 0)) %>%

    # NEW: Join with the pre-calculated CDS signature
    dplyr::left_join(cds_signatures, by = c("MET_ID" = "transcript_id")) %>%
    # Assign a unique placeholder for non-coding transcripts (no CDS feature)
    dplyr::mutate(CDS_Signature = tidyr::replace_na(CDS_Signature, "NON_CODING_MET"))


# --- 2. Pivot to Compare METs Side-by-Side and Filter ---
UTR5_Switch_Summary_DF <- MET_by_condition %>%
    
    # Pivot to align LM411 and LM511 METs side-by-side
    tidyr::pivot_wider(
        id_cols = c(gene_id, gene_name, Time_Point_of_Max_Shift),
        names_from = treat,
        values_from = c(MET_ID, MET_Biotype, UTR5_Length, CDS_Signature)
    ) %>%
    
    # Check for switches
    dplyr::mutate(
        # 1. MET ID must be different (Required: TRUE)
        ID_Switched = (MET_ID_LM411 != MET_ID_LM511),
        
        # 2. MET biotype must be the same (Required: FALSE)
        Biotype_Switched = (MET_Biotype_LM411 != MET_Biotype_LM511),
        
        # 3. 5' UTR length must be different (Required: TRUE)
        UTR5_Switched = (UTR5_Length_LM411 != UTR5_Length_LM511),
        
        # 4. CDS signature must be the same (Required: TRUE)
        CDS_Same = (CDS_Signature_LM411 == CDS_Signature_LM511)
    ) %>%
    
    # --- Filter to keep ONLY genes meeting the four criteria ---
    dplyr::filter(
        ID_Switched == TRUE,
        Biotype_Switched == FALSE,
        UTR5_Switched == TRUE,
        CDS_Same == TRUE
    ) %>%
    
    # Join the overall Max Delta Pi metric back for final prioritization
    dplyr::left_join(
        df_annotated %>% 
            dplyr::select(gene_id, Overall_Max_Delta_pi, adj_pvalue) %>% 
            dplyr::distinct(), 
        by = "gene_id"
    ) %>%
    
    # --- 3. Final Ordering and Selection ---
    
    # Sort by the magnitude of the shift
    dplyr::arrange(dplyr::desc(Overall_Max_Delta_pi)) %>%
    
    # Reorder and rename columns for a clean presentation
    dplyr::select(
        Gene_Symbol = gene_name,
        Gene_ID = gene_id,
        Max_Delta_pi = Overall_Max_Delta_pi,
        Adj_P_Value = adj_pvalue,
        Max_Shift_TimePoint = Time_Point_of_Max_Shift,
        
        # Side-by-side comparison columns:
        MET_ID_LM411,
        UTR5_Length_LM411,
        MET_ID_LM511,
        UTR5_Length_LM511,
        MET_Biotype_Common = MET_Biotype_LM411,
        
        # Confirmation flags
        ID_Switched,
        Biotype_Switched,
        UTR5_Switched,
        CDS_Same
    ) %>%
    
    # 4. Final Data Frame Conversion
    as.data.frame()

# Export the final list of gene names to be used by the visualization script
functional_switch_genes <- UTR5_Switch_Summary_DF$Gene_Symbol


# --- SAVE THE FINAL FILTERED SUMMARY TO TSV ---
write.table(
    UTR5_Switch_Summary_DF,
    file = "UTR5_ATSS_Switch_Summary.tsv", # The target file name
    sep = "\t", # Tab-separated format
    row.names = FALSE,
    quote = FALSE,
    na = "" # Write empty strings for NA values
)

cat("\n--- 5' UTR Alternative Transcription Start Site (ATSS) Switch Filtering Complete ---\n")
cat("Data frame 'UTR5_Switch_Summary_DF' has been saved to 'UTR5_ATSS_Switch_Summary.tsv'.\n")

# Print the top 5 5' UTR switches for review
cat("\nTop 5 5' UTR/ATSS Switch Genes (by Max Delta Pi):\n")
print(UTR5_Switch_Summary_DF[1:min(5, nrow(UTR5_Switch_Summary_DF)), ])

--- 5' UTR Alternative Transcription Start Site (ATSS) Switch Filtering Complete ---
Data frame 'UTR5_Switch_Summary_DF' has been saved to 'UTR5_ATSS_Switch_Summary.tsv'.

Top 5 5' UTR/ATSS Switch Genes (by Max Delta Pi):
  Gene_Symbol            Gene_ID Max_Delta_pi  Adj_P_Value Max_Shift_TimePoint
1     Rasgrp2 ENSMUSG00000032946   0.25396215 0.0023356292                  t4
2         Sla ENSMUSG00000022372   0.18116600 0.0000460725                  t0
3     St6gal1 ENSMUSG00000022885   0.09610355 0.0087323353                  t3
4     Tnfaip3 ENSMUSG00000019850   0.06327018 0.0180205806                  t3
        MET_ID_LM411 UTR5_Length_LM411       MET_ID_LM511 UTR5_Length_LM511
1 ENSMUST00000113476               248 ENSMUST00000167240               139
2 ENSMUST00000164163               383 ENSMUST00000100572               102
3 ENSMUST00000178797               485 ENSMUST00000023601               816
4 ENSMUST00000019997               273 ENSMUST00000105527               188
  MET_Biotype_Common ID_Switched Biotype_Switched UTR5_Switched CDS_Same
1     protein_coding        TRUE            FALSE          TRUE     TRUE
2     protein_coding        TRUE            FALSE          TRUE     TRUE
3     protein_coding        TRUE            FALSE          TRUE     TRUE
4     protein_coding        TRUE            FALSE          TRUE     TRUE

In [129]:
UTR5_Switch_Summary_DF

  Gene_Symbol Gene_ID            Max_Delta_pi Adj_P_Value  Max_Shift_TimePoint
1 Rasgrp2     ENSMUSG00000032946 0.25396215   0.0023356292 t4
2 Sla         ENSMUSG00000022372 0.18116600   0.0000460725 t0
3 St6gal1     ENSMUSG00000022885 0.09610355   0.0087323353 t3
4 Tnfaip3     ENSMUSG00000019850 0.06327018   0.0180205806 t3
  MET_ID_LM411       UTR5_Length_LM411 MET_ID_LM511       UTR5_Length_LM511
1 ENSMUST00000113476 248               ENSMUST00000167240 139
2 ENSMUST00000164163 383               ENSMUST00000100572 102
3 ENSMUST00000178797 485               ENSMUST00000023601 816
4 ENSMUST00000019997 273               ENSMUST00000105527 188
  MET_Biotype_Common ID_Switched Biotype_Switched UTR5_Switched CDS_Same
1 protein_coding     TRUE        FALSE            TRUE          TRUE
2 protein_coding     TRUE        FALSE            TRUE          TRUE
3 protein_coding     TRUE        FALSE            TRUE          TRUE
4 protein_coding     TRUE        FALSE            TRUE          TRUE

# Protein difference

In [134]:
# This script identifies genes where the Most Expressed Transcript (MET) switches between conditions,
# resulting in a different protein product (i.e., a change in the Ensembl Protein ID).

# --- PREREQUISITES ---
library(dplyr)
library(tidyr)
library(data.table)

# NOTE: This script assumes 'max_shift_long_data' and 'gtf_subset_rep' are loaded in the environment.

# --- 1. PREPARE GTF FOR PROTEIN ID MAPPING ---
# Extract unique transcript-to-protein mappings from the GTF (for CDS features)
transcript_to_protein_map <- gtf_subset_rep %>%
    filter(type == "CDS", protein_id != "") %>%
    # Select transcript_id and rename protein_id directly within select for robustness
    dplyr::select(transcript_id, Ensembl_Protein_ID = protein_id) %>%
    distinct()


# --- 2. IDENTIFY THE MET AND ITS PROTEIN ID PER CONDITION ---
# Use the annotated data frame (Max_Shift_Annotated_Transcripts.tsv)
df_annotated <- max_shift_long_data

MET_by_condition <- df_annotated %>%
    # Group by gene and treatment at the max shift time point
    group_by(gene_id, gene_name, Time_Point_of_Max_Shift, treat) %>%
    
    # Find the row with the maximum proportion (the MET)
    slice_max(order_by = proportion, n = 1, with_ties = FALSE) %>%
    ungroup() %>%
    
    # Select the key MET information
    dplyr::select(
        gene_id, gene_name, Time_Point_of_Max_Shift, treat,
        MET_ID = transcript_id,
        MET_Biotype = transcript_biotype
    ) %>%
    
    # Join the Protein ID (crucial for filtering)
    left_join(transcript_to_protein_map, by = c("MET_ID" = "transcript_id"))


# --- 3. PIVOT AND FILTER FOR PROTEIN SWITCHES ---
CDS_Protein_Switch_Summary_DF <- MET_by_condition %>%
    
    # Pivot to align LM411 and LM511 METs side-by-side
    pivot_wider(
        id_cols = c(gene_id, gene_name, Time_Point_of_Max_Shift),
        names_from = treat,
        values_from = c(MET_ID, MET_Biotype, Ensembl_Protein_ID)
    ) %>%
    
    # Check for switches
    mutate(
        ID_Switched = (MET_ID_LM411 != MET_ID_LM511),
        Biotype_Switched = (MET_Biotype_LM411 != MET_Biotype_LM511),
        # CRITICAL FILTER: Check if the resulting protein ID is different
        Protein_ID_Switched = (Ensembl_Protein_ID_LM411 != Ensembl_Protein_ID_LM511)
    ) %>%
    
    # Filter to keep ONLY genes where the ID switched AND the Protein ID switched
    filter(ID_Switched == TRUE, Protein_ID_Switched == TRUE) %>%
    
    # Join the overall Max Delta Pi metric back for final prioritization
    left_join(
        df_annotated %>%
            dplyr::select(gene_id, Overall_Max_Delta_pi) %>%
            distinct(),
        by = "gene_id"
    ) %>%
    
    # --- 4. Final Ordering and Selection ---
    arrange(desc(Overall_Max_Delta_pi)) %>%
    dplyr::select(
        Gene_Symbol = gene_name,
        Gene_ID = gene_id,
        Max_Delta_pi = Overall_Max_Delta_pi,
        Max_Shift_TimePoint = Time_Point_of_Max_Shift,
        
        MET_ID_LM411,
        Ensembl_Protein_ID_LM411,
        MET_ID_LM511,
        Ensembl_Protein_ID_LM511,
        Protein_ID_Switched
    ) %>%
    as.data.frame()

# --- 5. Save the Filtered List (The required dependency file) ---
fwrite(CDS_Protein_Switch_Summary_DF, file = "CDS_Protein_Switch_Summary.tsv", sep = "\t")

print("Successfully generated and saved the list of CDS-Altering Protein Switches.")
print("File saved as: 'CDS_Protein_Switch_Summary.tsv'")
head(CDS_Protein_Switch_Summary_DF)

[1] "Successfully generated and saved the list of CDS-Altering Protein Switches."
[1] "File saved as: 'CDS_Protein_Switch_Summary.tsv'"

  Gene_Symbol Gene_ID            Max_Delta_pi Max_Shift_TimePoint
1 Pla2g4c     ENSMUSG00000033847 0.6062322    t2
2 Loxl3       ENSMUSG00000000693 0.4091251    t4
3 Cage1       ENSMUSG00000044566 0.4008715    t0
4 Stard9      ENSMUSG00000033705 0.3326730    t3
5 Nrn1        ENSMUSG00000039114 0.3189587    t2
6 Mcm9        ENSMUSG00000058298 0.2926154    t1
  MET_ID_LM411       Ensembl_Protein_ID_LM411 MET_ID_LM511
1 ENSMUST00000108528 ENSMUSP00000104168       ENSMUST00000043612
2 ENSMUST00000000707 ENSMUSP00000000707       ENSMUST00000101257
3 ENSMUST00000110233 ENSMUSP00000105862       ENSMUST00000089840
4 ENSMUST00000180041 ENSMUSP00000136055       ENSMUST00000154193
5 ENSMUST00000223611 ENSMUSP00000153395       ENSMUST00000037623
6 ENSMUST00000237608 ENSMUSP00000157761       ENSMUST00000075540
  Ensembl_Protein_ID_LM511 Protein_ID_Switched
1 ENSMUSP00000043672       TRUE
2 ENSMUSP00000098815       TRUE
3 ENSMUSP00000087278       TRUE
4 ENSMUSP00000116900       TRUE
5 ENSMUSP00000040900       TRUE
6 ENSMUSP00000074978       TRUE

In [140]:
# This script is specifically designed to query BioMart for functional annotations (Domains, PTMs, TM regions)
# ONLY for the proteins involved in a statistically significant CDS-altering MET switch.

# --- PREREQUISITES ---
# Load necessary libraries (assuming biomaRt, dplyr, and data.table are installed)
library(biomaRt)
library(dplyr)
library(data.table)

# --- STEP 1: Load the Filtered List of CDS-Switching METs ---
cat("Loading CDS switch summary to identify relevant proteins...\n")

# Check if the object is already in memory (as created by the previous filtering script)
if (exists("CDS_Protein_Switch_Summary_DF")) {
    cds_switch_summary <- CDS_Protein_Switch_Summary_DF
    cat("Using in-memory object 'CDS_Protein_Switch_Summary_DF'.\n")
} else if (file.exists("CDS_Protein_Switch_Summary.tsv")) {
    # Fallback: Load from the file if it exists
    cds_switch_summary <- as.data.frame(fread("CDS_Protein_Switch_Summary.tsv"))
    cat("Loaded 'CDS_Protein_Switch_Summary.tsv'.\n")
} else {
    stop("Error: CDS switch data not found. Neither in-memory object 'CDS_Protein_Switch_Summary_DF' nor file 'CDS_Protein_Switch_Summary.tsv' was found.")
}


# --- STEP 2: Extract all unique Protein IDs from the Switched METs ---

# Extract all unique Ensembl Protein IDs involved in the switch
all_protein_ids <- c(
    cds_switch_summary$Ensembl_Protein_ID_LM411, 
    cds_switch_summary$Ensembl_Protein_ID_LM511
) %>% unique() %>% na.omit() %>% as.character()

if (length(all_protein_ids) == 0) {
    stop("Error: No valid Ensembl Protein IDs found for the switched METs.")
}

print(paste("Found a highly focused list of", length(all_protein_ids), "unique Ensembl Protein IDs to query."))


# --- STEP 3: Set up the BioMart Connection ---
# IMPORTANT: Change 'mmusculus_gene_ensembl' to your organism if necessary!
ensembl <- useEnsembl(
    biomart = "ensembl", 
    dataset = "mmusculus_gene_ensembl", 
    version = 111
)

# --- STEP 4: Retrieve Annotations from Ensembl for ONLY the Switched Proteins ---
cat("Querying BioMart for Domains (Pfam/InterPro)...\n")
annotation_data <- getBM(
    attributes = c(
        "ensembl_peptide_id",
        "interpro_description",
        "pfam"
    ),
    filters = "ensembl_peptide_id",
    values = all_protein_ids, # <-- Uses the highly filtered list
    mart = ensembl
)

# --- STEP 5: Aggregate all Functional Features into a Single String ---

# Clean up PTM/Feature data and aggregate all features (Domains, PTMs, TM, etc.)
domain_map_for_filtering <- annotation_data %>%
    # Filter out empty or uninformative rows, focusing on InterPro and Pfam only
    filter(!is.na(interpro_description) | !is.na(pfam)) %>%
    
    # Generate a descriptive feature string for aggregation
    mutate(
        Feature_Type = case_when(
            !is.na(interpro_description) ~ paste0("IPRO:", interpro_description),
            !is.na(pfam) ~ paste0("PFAM:", pfam),
            TRUE ~ NA_character_
        )
    ) %>%
    
    # Group by protein and summarize all features into one unique, sorted string
    group_by(Protein_ID = ensembl_peptide_id) %>%
    summarise(
        Domain_Structure_String = paste(sort(unique(na.omit(Feature_Type))), collapse = "|"),
        .groups = 'drop'
    )

# --- STEP 6: Final Cleanup and Saving ---

final_domain_map <- domain_map_for_filtering %>%
    dplyr::select(
        Protein_ID, 
        Domain_Structure_String
    ) %>%
    as.data.frame()

# Save the map as the required input file
fwrite(final_domain_map, file = "Protein_Domain_Annotations.tsv", sep = "\t")

print("\nSuccessfully generated the highly focused protein domain map!")
print("File saved as: 'Protein_Domain_Annotations.tsv' (only includes proteins from switched METs).")
head(final_domain_map)

Loading CDS switch summary to identify relevant proteins...
Using in-memory object 'CDS_Protein_Switch_Summary_DF'.
[1] "Found a highly focused list of 58 unique Ensembl Protein IDs to query."
Querying BioMart for Domains (Pfam/InterPro)...
[1] "\nSuccessfully generated the highly focused protein domain map!"
[1] "File saved as: 'Protein_Domain_Annotations.tsv' (only includes proteins from switched METs)."

  Protein_ID
1 ENSMUSP00000000707
2 ENSMUSP00000005399
3 ENSMUSP00000010241
4 ENSMUSP00000019997
5 ENSMUSP00000020173
6 ENSMUSP00000023601
  Domain_Structure_String
1 IPRO:Lysyl oxidase|IPRO:Lysyl oxidase, conserved site|IPRO:SRCR domain|IPRO:SRCR-like domain|IPRO:SRCR-like domain superfamily
2 IPRO:KRAB domain superfamily|IPRO:Krueppel-associated box|IPRO:SCAN domain|IPRO:SCAN domain superfamily|IPRO:Zinc finger C2H2 superfamily|IPRO:Zinc finger C2H2-type
3 IPRO:Leucine-rich repeat|IPRO:Leucine-rich repeat domain superfamily|IPRO:NTF2-like domain superfamily|IPRO:Nuclear RNA export factor|IPRO:Nuclear RNA export factor Tap, RNA-binding domain|IPRO:Nuclear transport factor 2 domain|IPRO:Nuclear transport factor 2, eukaryote|IPRO:Nucleotide-binding alpha-beta plait domain superfamily|IPRO:RNA-binding domain superfamily|IPRO:TAP C-terminal (TAP-C) domain|IPRO:UBA-like superfamily
4 IPRO:OTU domain|IPRO:Zinc finger, A20-type
5 IPRO:Microtubule-associated protein 7 family
6 IPRO:Glycosyl transferase family 29|IPRO:GT29-like superfamiliy|IPRO:Sialyltransferase

In [ ]:
# Example Concept for UniProt.ws (requires package installation)

# 1. Map Ensembl Peptide ID to UniProt Accession
# You would use mapIds from AnnotationDbi or use the existing BiomaRt column (if available).

# 2. Query the UniProt Feature Table
# library(UniProt.ws)
# up <- UniProt.ws(taxId=10090) # Mouse
# features <- getFeatureEntry(up, unipro_accession, featureType=c("MOD_RES", "TRANSMEM"))

# New plots

sessionInfo()

In [66]:
# NOTE: This script assumes required packages (ggplot2, dplyr, tidyr, cowplot, ggtranscript, etc.) are loaded.
# Dataframes required: max_shift_long_data, gtf_subset_rep, normalized_counts_transcript_subset, 
# normalized_counts_genes_subset, DGE_result_subset, DTE_result_subset.

# ----------------------------------------------------------------------------------
# --- 1. DEFINE HELPER FUNCTION ---
create_transcript_label <- function(id, biotype, tag, ccds) {
    id <- as.character(id)
    tag <- if (is.null(tag) || length(tag) == 0 || is.na(tag)) "" else as.character(tag)
    ccds <- if (is.null(ccds) || length(ccds) == 0 || is.na(ccds)) "" else as.character(ccds)
    short_id <- substr(id, nchar(id) - 3, nchar(id))
    parts <- c(paste(short_id, biotype, sep = "\n"))
    if (tag != "") {
        parts <- c(parts, tag)
    }
    if (ccds != "") {
        parts <- c(parts, ccds) 
    }
    return(paste(parts, collapse = "\n"))
}
# ----------------------------------------------------------------------------------

# --- 2. Define Universal Plotting Constants and Setup ---
breaks.Rank <- (seq(0, 1, by = 0.25))
labels.Rank <- as.character(breaks.Rank)
AXIS_STROKE_MM <- 0.176 
LABEL_FONT_SIZE_MM <- 6 / ggplot2::.pt

if (!exists("path_graphs")) {
    path_graphs <- "Graphs"
}

# Setup output directory and gene list
all_dtu_genes <- unique(max_shift_long_data$gene_name)
all_dtu_genes <- all_dtu_genes[!is.na(all_dtu_genes) & all_dtu_genes != ""]
output_dir <- path_graphs

if (!dir.exists(output_dir)) {
    dir.create(output_dir)
    cat(paste0("Created directory: ", output_dir, "\n"))
}

# Global GTF Pre-Filtering (same as previous script)
if ('seqid' %in% colnames(gtf_subset_rep)) {
    colnames(gtf_subset_rep)[which(colnames(gtf_subset_rep) == 'seqid')]<-'seqnames'
}
gtf_subset_rep$seqnames <- as.character(gtf_subset_rep$seqnames)
canonical_chromosomes <- c(as.character(1:22), "X", "Y", "M", "MT")
gtf_subset_rep <- gtf_subset_rep %>%
    dplyr::filter(seqnames %in% canonical_chromosomes)
cat(paste0("Pre-filtering GTF data: Filtered to only canonical seqnames.\n"))

# ----------------------------------------------------------------------------------
# --- 3. DESEQ2 DATA PREPARATION (Converting WIDE -> LONG and Creating Lookups) ---
# ----------------------------------------------------------------------------------
cat("\nPreparing DESeq2 normalized counts data for plotting...\n")

# --- 3.1. Gene Counts Conversion ---
deseq_gene_counts_wide <- normalized_counts_genes_subset 
gene_sample_cols <- setdiff(colnames(deseq_gene_counts_wide), "gene_name")

deseq_gene_counts_long <- deseq_gene_counts_wide %>%
    tidyr::pivot_longer(
        cols = all_of(gene_sample_cols), 
        names_to = "sample_time", 
        values_to = "normalized_count"
    ) %>%
    dplyr::mutate(
        treat = sub("_R[0-9]+_t[0-9]+", "", sample_time), 
        time_point = sub(".*(t[0-9]+)$", "\\1", sample_time), 
        sample = sample_time
    ) %>%
    dplyr::select(gene_name, sample, normalized_count, treat, time_point)
cat(paste0("Gene counts converted to long format (", nrow(deseq_gene_counts_long), " rows).\n"))

# --- 3.2. Transcript Counts Conversion ---
deseq_transcript_counts_wide <- normalized_counts_transcript_subset 
transcript_sample_cols <- setdiff(colnames(deseq_transcript_counts_wide), "transcript_id")

deseq_transcript_counts_long <- deseq_transcript_counts_wide %>%
    tidyr::pivot_longer(
        cols = all_of(transcript_sample_cols), 
        names_to = "sample_time", 
        values_to = "normalized_count"
    ) %>%
    dplyr::mutate(
        treat = sub("_R[0-9]+_t[0-9]+", "", sample_time), 
        time_point = sub(".*(t[0-9]+)$", "\\1", sample_time), 
        sample = sample_time
    ) %>%
    dplyr::select(transcript_id, sample, normalized_count, treat, time_point)
cat(paste0("Transcript counts converted to long format (", nrow(deseq_transcript_counts_long), " rows).\n"))

# --- 3.3. Prepare DGE result lookup table (for Gene Plot Title) ---
DGE_lookup <- DGE_result_subset %>%
    dplyr::select(gene_name, minuslog10padj) %>%
    # UPDATED: Round to 1 decimal place
    dplyr::mutate(minuslog10padj_rounded = round(minuslog10padj, 1)) %>% 
    dplyr::distinct()
cat(paste0("DGE lookup table created (", nrow(DGE_lookup), " rows).\n"))

# --- 3.4. Prepare DTE transcript result lookup table (for Transcript Plot Labels) ---
DTE_lookup <- DTE_result_subset %>%
    dplyr::select(transcript_id, minuslog10padj) %>%
    # UPDATED: Round to 1 decimal place
    dplyr::mutate(minuslog10padj_rounded = round(minuslog10padj, 1)) %>%
    dplyr::distinct()
cat(paste0("DTE lookup table created (", nrow(DTE_lookup), " rows).\n"))

# ----------------------------------------------------------------------------------
# --- 4. Iteration Loop: Process, Plot, and Save Combined Figures ---
# ----------------------------------------------------------------------------------

cat("\nStarting iterative combined plot generation...\n")
plot_count <- 0

for (gene in all_dtu_genes) {
    
    # --- GENE EXCLUSION MECHANISM ---
    GENES_TO_EXCLUDE <- c('Lcorl;Gm3414','Nupl1','Gramd3') 
    if (gene %in% GENES_TO_EXCLUDE) {
        cat(paste0("Skipping Gene: ", gene, " (Manually excluded).\n"))
        next 
    }
    # --- END EXCLUSION MECHANISM ---
    
    cat(paste0("Processing Gene: ", gene, "...\n"))
    
    # --- 4.1. Data Preparation for Current Gene (Proportion Plot) ---
    gene_data <- max_shift_long_data %>% 
        filter(gene_name == gene) %>%
        mutate(treat = factor(treat, levels = c("LM411", "LM511")))
    
    gene_data_labeled <- gene_data %>%
        mutate(
            transcript_id = as.character(transcript_id),
            display_label = paste0(transcript_id, "\n(prop. = ", round(proportion, 2), ")")
        )

    max_delta <- unique(gene_data_labeled$Overall_Max_Delta_pi)
    adj_pvalue <- unique(gene_data_labeled$adj_pvalue)[1]
    
    depicted_order <- gene_data_labeled %>%
        dplyr::select(transcript_id, display_label) %>%
        distinct() %>%
        arrange(desc(transcript_id))
        
    display_label_order <- depicted_order %>% pull(display_label)
    transcript_id_order_from_prop <- unique(gsub("\n.*", "", display_label_order)) 
    
    gene_data_labeled$display_label <- factor(gene_data_labeled$display_label, 
                                             levels = display_label_order, 
                                             ordered = TRUE)
    
    
    # --- 4.2. Plot 1: Proportion Bar Plot (p) ---
    p <- ggplot(data = gene_data_labeled,
                aes(x = treat, y = proportion)) +
        
        geom_bar(stat = "identity", fill = "lightgray", colour = 'black') +
        
        geom_text(aes(label = display_label),
                  position = position_stack(vjust = 0.5),
                  size = LABEL_FONT_SIZE_MM,
                  color = "black",
                  family = "sans") +
        
        scale_y_continuous(name = paste("DRIMseq modelled proportion", sep = " "),
                           breaks = breaks.Rank,
                           labels = labels.Rank) + 
        
        labs(
            title = bquote(.(gene) * " (DTU: " * Delta * pi * "=" * .(round(max_delta, 3)) * ", Adj P=" * .(round(adj_pvalue, 3)) * ")"),
            x = "Treatment Group"
        ) +
        theme_classic() +
        
        theme(title = element_text(size = 8, color = "black", family = "sans"),
              axis.title.y = element_text(size = 8, color = "black", family = "sans"),
              axis.title.x = element_blank(),
              axis.text.y = element_text(angle = 0, size = 6, color = "black", family = "sans"),
              axis.text.x = element_text(angle = 0, size = 6, color = "black", family = "sans"),
              axis.line.x = element_line(size = AXIS_STROKE_MM),
              axis.ticks.x = element_line(size = AXIS_STROKE_MM),
              axis.ticks.y = element_line(size = AXIS_STROKE_MM),
              axis.line.y = element_line(size = AXIS_STROKE_MM),
              legend.position = "none")
              
    
    # ----------------------------------------------------------------------------------
    # --- 4.3. DESEQ2 EXPRESSION PLOTS (GENE & TRANSCRIPT) ---
    # ----------------------------------------------------------------------------------

    # Find the time point of max shift (used for filtering expression data)
    time_point_column <- "Time_Point_of_Max_Shift" 
    temp_tp_vec <- unique(gene_data[[time_point_column]])
    valid_tp <- temp_tp_vec[!is.na(temp_tp_vec) & temp_tp_vec != ""]
    
    if (length(valid_tp) == 0) {
        max_shift_tp <- "All"
    } else {
        max_shift_tp <- as.character(valid_tp[1])
    }
    
    
    # --- 4.3.A. GENE EXPRESSION PLOT (UPDATED TITLE) ---
    
    # 1. Fetch the DGE P-value for the title
    current_dge_padj <- DGE_lookup %>% 
        dplyr::filter(gene_name == gene) %>% 
        dplyr::pull(minuslog10padj_rounded)
        
    # Handle case where DGE result is missing
    dge_label <- if(length(current_dge_padj) > 0) {
        # Formatting to ensure one decimal place is displayed, even if it's .0
        paste0("-log10pval = ", format(current_dge_padj[1], nsmall=1)) 
    } else {
        "DGE N/A"
    }
    
    # 2. Filter gene expression data (same as before)
    gene_expr_data <- deseq_gene_counts_long %>%
        dplyr::filter(gene_name == gene, time_point == max_shift_tp) %>%
        dplyr::mutate(treat = factor(treat, levels = c("LM411", "LM511")))
    
    if (nrow(gene_expr_data) == 0) {
        # Placeholder if data is missing
        p_gene_expr <- ggplot() + 
            annotate("text", x=1, y=1, label=paste("Gene Expression Missing\n", dge_label), size=3) + 
            theme_classic() + labs(y="Log Norm. Count", x="")
        cat(paste0("Warning: Gene expression data missing for ", gene, " at ", max_shift_tp, ". Using placeholder.\n"))
    } else {
        p_gene_expr <- ggplot(data = gene_expr_data, 
                              aes(x = treat, y = log10(normalized_count + 1), fill = treat)) +
            geom_boxplot(alpha=0.5, outlier.shape = NA) + 
            geom_jitter(width=0.15, size=1.5, alpha=0.7) +
            labs(y=expression(log[10](paste("Gene Norm. Count + 1"))), 
                 x=paste("Treatment at", max_shift_tp),
                 title = dge_label) +
            scale_fill_manual(values = c("LM411" = "#1f78b4", "LM511" = "#e31a1c")) +
            theme_classic() + 
            theme(legend.position = "none", 
                  plot.title = element_text(size = 8, hjust = 0.5), 
                  axis.title.y=element_text(size=8), 
                  axis.title.x=element_text(size=8),
                  axis.text=element_text(size=6))
    }
    
    
    # --- 4.3.B. TRANSCRIPT EXPRESSION PLOT (UPDATED with DTE labels) ---

    transcript_expr_data <- deseq_transcript_counts_long %>%
        dplyr::filter(transcript_id %in% transcript_id_order_from_prop, time_point == max_shift_tp) %>%
        dplyr::mutate(treat = factor(treat, levels = c("LM411", "LM511")))

    transcript_expr_data$transcript_id <- factor(transcript_expr_data$transcript_id, 
                                                levels = transcript_id_order_from_prop, 
                                                ordered = TRUE)

    if (nrow(transcript_expr_data) == 0) {
         p_transcript_expr <- ggplot() + annotate("text", x=1, y=1, label="Transcript Expression Data Missing", size=3) + theme_classic() + labs(y="Log Norm. Count", x="")
         cat(paste0("Warning: Transcript expression data missing for ", gene, " at ", max_shift_tp, ". Using placeholder.\n"))
    } else {
        
        # 1. Merge DTE P-value for the label
        transcript_expr_data_labeled <- transcript_expr_data %>%
            dplyr::left_join(DTE_lookup, by = "transcript_id") %>%
            dplyr::mutate(
                dte_label = ifelse(
                    is.na(minuslog10padj_rounded), 
                    "-log10pval = N/A", 
                    # Formatting to ensure one decimal place is displayed
                    paste0("-log10pval = ", format(minuslog10padj_rounded, nsmall=1))
                )
            )

        # 2. Determine plot limits for positioning the geom_text label
        y_max <- max(log10(transcript_expr_data_labeled$normalized_count + 1), na.rm = TRUE)
        y_pos <- y_max * 0.95 # Position near the top

        # 3. Create the plot with geom_text
        p_transcript_expr <- ggplot(data = transcript_expr_data_labeled, 
                                    aes(x = treat, y = log10(normalized_count + 1), fill = treat)) +
            geom_boxplot(alpha=0.5, outlier.shape = NA) + 
            geom_jitter(width=0.15, size=1.5, alpha = 0.7) +
            
            # --- ADD DTE P-value label inside each facet ---
            geom_text(
                data = transcript_expr_data_labeled %>% 
                       dplyr::select(transcript_id, dte_label) %>% 
                       dplyr::distinct(),
                aes(x = 1.5, y = y_pos, label = dte_label),
                inherit.aes = FALSE,
                size = 2, 
                hjust = 0.5,
                vjust = 1
            ) +
            # -----------------------------------------------
            
            facet_wrap(~ transcript_id, nrow = 1, strip.position = "top") +
            labs(y=expression(log[10](paste("Tx Norm. Count + 1"))), 
                 x=paste("Treatment Group")) +
            scale_fill_manual(values = c("LM411" = "#1f78b4", "LM511" = "#e31a1c"), name = "Treatment") +
            theme_classic() + 
            theme(legend.position = "bottom", 
                  axis.title.y=element_text(size=8), 
                  axis.title.x=element_blank(), 
                  axis.text.y=element_text(size=6), 
                  axis.text.x=element_blank(), 
                  axis.ticks.x=element_blank(), 
                  strip.text = element_text(size=6),
                  strip.background = element_rect(fill = "gray95", color = "gray50"),
                  legend.text = element_text(size=7))
    }
    
    # ----------------------------------------------------------------------------------

    # --- 4.4. Transcript Structure Plot (transcript_plot) (No Change) ---

    REP_ggtranscript <- gtf_subset_rep %>% 
        dplyr::filter(gene_name == gene) %>%
        droplevels()

    if ('seqid' %in% colnames(REP_ggtranscript)) {
        colnames(REP_ggtranscript)[which(colnames(REP_ggtranscript) == 'seqid')]<-'seqnames'
    }
    REP_ggtranscript$seqnames <- as.character(REP_ggtranscript$seqnames)

    # PER-GENE SAFEGUARD FILTER 
    unique_seqnames_gene <- unique(REP_ggtranscript$seqnames)
    if (length(unique_seqnames_gene) > 1) {
        canonical_seqname_gene <- REP_ggtranscript %>%
            dplyr::group_by(seqnames) %>%
            dplyr::summarise(n = n(), .groups = 'drop') %>%
            dplyr::arrange(desc(n)) %>%
            dplyr::slice_head(n = 1) %>% 
            dplyr::pull(seqnames)
            
        REP_ggtranscript <- REP_ggtranscript %>% dplyr::filter(seqnames == canonical_seqname_gene)
        REP_ggtranscript$seqnames <- canonical_seqname_gene 
        
        cat(paste0("Warning: Gene ", gene, " seqnames coerced to: ", canonical_seqname_gene, ".\n"))
    }
    
    if(length(unique(REP_ggtranscript$seqnames)) > 1) {
        cat(paste0("CRITICAL FAILURE: Gene ", gene, " is still annotated on multiple seqnames. Skipping plot.\n"))
        next 
    }
    
    # Pre-calculate the multi-line Y-axis label
    REP_ggtranscript <- REP_ggtranscript %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            transcript_label = create_transcript_label(
                transcript_id, 
                transcript_biotype, 
                tag, 
                ccds_id
            )
        ) %>%
        dplyr::ungroup()
    
    # Create a temporary data frame to pull transcript labels in the desired 'depicted_order'
    label_lookup <- REP_ggtranscript %>% 
        dplyr::select(transcript_id, transcript_label) %>%
        dplyr::distinct() %>%
        dplyr::left_join(depicted_order, by = "transcript_id") %>%
        dplyr::filter(!is.na(display_label)) %>% 
        dplyr::arrange(display_label) %>%
        dplyr::pull(transcript_label)
        
    label_levels <- unique(as.character(label_lookup)) 
    
    REP_ggtranscript$transcript_label <- factor(REP_ggtranscript$transcript_label,
                                                 levels = label_levels,
                                                 ordered = TRUE)
    
    # TRANSCRIPT PLOTTING
    REP_exons <- REP_ggtranscript %>% dplyr::filter(type == "exon")

    if(length(unique(REP_exons$seqnames)) > 1) {
        cat(paste0("CRITICAL FAILURE (Exons): Gene ", gene, " is still annotated on multiple seqnames in the REP_exons object. Skipping plot.\n"))
        next 
    }
    
    REP_exons_rescaled <- shorten_gaps(
        REP_exons, 
        to_intron(REP_exons, "transcript_label"), 
        group_var = "transcript_label" 
    )
    
    transcript_plot <- REP_exons_rescaled %>%
        dplyr::filter(type == "exon") %>%
        ggplot(aes(
            xstart = start,
            xend = end,
            y = transcript_label 
        )) +
        scale_y_discrete() + 
        geom_range(height = 0.25,
            fill="steelblue"
        ) +
        geom_intron(
            data = REP_exons_rescaled %>% dplyr::filter(type == "intron"),
            aes(strand=strand),
            arrow = grid::arrow(ends = "last", length = grid::unit(0.25, "cm")),
            arrow.min.intron.length = 200
        )
    
    # THEME APPLICATION
    transcript_plot <- transcript_plot +
        theme_classic() +
        theme(
            axis.title.y=element_blank(),
            axis.title.x=element_blank(),
            axis.text.y=element_text(angle=0,size=8, color="black", family="sans"),
            axis.text.x=element_text(angle=0,size=8, color="black", family="sans"),
            axis.line.x = element_line(size = 0.4),
            axis.ticks = element_line(size = 0.4),
            axis.line.y = element_line(size = 0.4)
        ) +
        theme(
            legend.title = element_blank(),
            legend.text = element_text(size=6),
            legend.key.size = unit(0.25, 'cm'),
            legend.key.height = unit(0.25, 'cm'),
            legend.key.width = unit(0.25, 'cm'),
            legend.position="bottom"
        )
    
    
    # --- 4.5. Combine ALL Plots Side-by-Side ---
    # The layout is now: Proportion (1.5) | Gene Expr (1.2) | Transcript Expr (2.8) | Structure (3.0)
    combined_plot <- cowplot::plot_grid(p, p_gene_expr, p_transcript_expr, transcript_plot, 
                                     nrow = 1, 
                                     rel_widths = c(1.5, 1.2, 2.8, 3.0), 
                                     align = 'h', axis = 'l')

    # 4.5.B. Save R Plot Object (.rds)
    rds_filename <- file.path(output_dir, paste0(gene, "_Combined_Plot_Object.rds"))
    
    # ⭐ Action: Saving the 'combined_plot' object
    saveRDS(combined_plot, file = rds_filename)
    
    cat(paste0("   -> Saved plot object to: ", rds_filename, "\n"))


       
    # --- 4.6. Save Combined Figure ---
    filename <- file.path(output_dir, paste0(gene, "_DTU_Combined_Plot.svg"))
    
    ggsave(filename, 
           plot = combined_plot, 
           device = "svg", 
           width = 18, 
           height = 6, 
           units = "in")
    
    plot_count <- plot_count + 1
} 

cat(paste0("\n✅ Successfully finished processing ", plot_count, " individual DTU genes and saved combined figures to the '", output_dir, "' folder.\n"))

Pre-filtering GTF data: Filtered to only canonical seqnames.

Preparing DESeq2 normalized counts data for plotting...
Gene counts converted to long format (4260 rows).
Transcript counts converted to long format (12660 rows).
DGE lookup table created (142 rows).
DTE lookup table created (422 rows).

Starting iterative combined plot generation...
Processing Gene: Loxl3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Loxl3_Combined_Plot_Object.rds
Processing Gene: Ocel1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ocel1_Combined_Plot_Object.rds
Processing Gene: Stk11...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Stk11_Combined_Plot_Object.rds
Processing Gene: Ogdh...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ogdh_Combined_Plot_Object.rds
Processing Gene: Fosb...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Fosb_Combined_Plot_Object.rds
Processing Gene: Sin3b...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sin3b_Combined_Plot_Object.rds
Processing Gene: U2af2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//U2af2_Combined_Plot_Object.rds
Processing Gene: Zfp287...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Zfp287_Combined_Plot_Object.rds
Processing Gene: Chmp2a...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Chmp2a_Combined_Plot_Object.rds
Processing Gene: Kmt2b...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Kmt2b_Combined_Plot_Object.rds
Processing Gene: Rps9...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rps9_Combined_Plot_Object.rds
Processing Gene: Bcl2l1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Bcl2l1_Combined_Plot_Object.rds
Processing Gene: Fxyd5...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Fxyd5_Combined_Plot_Object.rds
Processing Gene: Nxf1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nxf1_Combined_Plot_Object.rds
Skipping Gene: Lcorl;Gm3414 (Manually excluded).
Processing Gene: Cyth1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Cyth1_Combined_Plot_Object.rds
Processing Gene: Kansl1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Kansl1_Combined_Plot_Object.rds
Processing Gene: Tnfaip3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tnfaip3_Combined_Plot_Object.rds
Processing Gene: Map7...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Map7_Combined_Plot_Object.rds
Processing Gene: Nin...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nin_Combined_Plot_Object.rds
Processing Gene: Nedd9...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nedd9_Combined_Plot_Object.rds
Processing Gene: Scamp1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Scamp1_Combined_Plot_Object.rds
Processing Gene: Zmym2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Zmym2_Combined_Plot_Object.rds
Processing Gene: Slc25a32...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Slc25a32_Combined_Plot_Object.rds
Processing Gene: St6gal1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//St6gal1_Combined_Plot_Object.rds
Processing Gene: Nr4a1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nr4a1_Combined_Plot_Object.rds
Processing Gene: Brd2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Brd2_Combined_Plot_Object.rds
Processing Gene: Smad2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Smad2_Combined_Plot_Object.rds
Processing Gene: Cdk2ap2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Cdk2ap2_Combined_Plot_Object.rds
Processing Gene: Ctsw...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ctsw_Combined_Plot_Object.rds
Processing Gene: Tm9sf3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tm9sf3_Combined_Plot_Object.rds
Processing Gene: Nab2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nab2_Combined_Plot_Object.rds
Processing Gene: Rptor...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rptor_Combined_Plot_Object.rds
Processing Gene: Shisa5...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Shisa5_Combined_Plot_Object.rds
Processing Gene: Adipor1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Adipor1_Combined_Plot_Object.rds
Processing Gene: Rbl1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rbl1_Combined_Plot_Object.rds
Processing Gene: Trim33...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Trim33_Combined_Plot_Object.rds
Processing Gene: Zdhhc21...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Zdhhc21_Combined_Plot_Object.rds
Processing Gene: Rer1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rer1_Combined_Plot_Object.rds
Processing Gene: Arhgdib...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Arhgdib_Combined_Plot_Object.rds
Processing Gene: Ctsc...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ctsc_Combined_Plot_Object.rds
Processing Gene: Rps6ka3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rps6ka3_Combined_Plot_Object.rds
Processing Gene: Psmb10...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Psmb10_Combined_Plot_Object.rds
Processing Gene: Pdcd6ip...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Pdcd6ip_Combined_Plot_Object.rds
Processing Gene: Rasgrp2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rasgrp2_Combined_Plot_Object.rds
Processing Gene: Nfatc1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nfatc1_Combined_Plot_Object.rds
Processing Gene: Plekhj1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Plekhj1_Combined_Plot_Object.rds
Processing Gene: Nrn1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Nrn1_Combined_Plot_Object.rds
Processing Gene: Tbc1d25...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tbc1d25_Combined_Plot_Object.rds
Processing Gene: Med12l...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Med12l_Combined_Plot_Object.rds
Processing Gene: Trim46...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Trim46_Combined_Plot_Object.rds
Processing Gene: Tm6sf1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tm6sf1_Combined_Plot_Object.rds
Skipping Gene: Nupl1 (Manually excluded).
Processing Gene: Dicer1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dicer1_Combined_Plot_Object.rds
Processing Gene: Hdlbp...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Hdlbp_Combined_Plot_Object.rds
Processing Gene: Pla2g4c...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Pla2g4c_Combined_Plot_Object.rds
Processing Gene: Tex264...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tex264_Combined_Plot_Object.rds
Processing Gene: Wapl...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Wapl_Combined_Plot_Object.rds
Processing Gene: Ttc39b...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ttc39b_Combined_Plot_Object.rds
Processing Gene: Mtmr7...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Mtmr7_Combined_Plot_Object.rds
Processing Gene: Prkar1a...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Prkar1a_Combined_Plot_Object.rds
Processing Gene: Akap8l...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Akap8l_Combined_Plot_Object.rds
Processing Gene: Hnrnph2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Hnrnph2_Combined_Plot_Object.rds
Processing Gene: Ascc1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ascc1_Combined_Plot_Object.rds
Processing Gene: Polr1d...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Polr1d_Combined_Plot_Object.rds
Processing Gene: Exoc4...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Exoc4_Combined_Plot_Object.rds
Processing Gene: Ggnbp1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Ggnbp1_Combined_Plot_Object.rds
Processing Gene: Sp100...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sp100_Combined_Plot_Object.rds
Processing Gene: Arhgef39...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Arhgef39_Combined_Plot_Object.rds
Processing Gene: Fubp3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Fubp3_Combined_Plot_Object.rds
Processing Gene: Themis...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Themis_Combined_Plot_Object.rds
Processing Gene: Susd3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Susd3_Combined_Plot_Object.rds
Processing Gene: Dnah10...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dnah10_Combined_Plot_Object.rds
Processing Gene: Rbm33...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rbm33_Combined_Plot_Object.rds
Processing Gene: Gpcpd1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Gpcpd1_Combined_Plot_Object.rds
Processing Gene: Fyn...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Fyn_Combined_Plot_Object.rds
Processing Gene: Dgcr6...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dgcr6_Combined_Plot_Object.rds
Processing Gene: Tnrc6b...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Tnrc6b_Combined_Plot_Object.rds
Processing Gene: Kcmf1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Kcmf1_Combined_Plot_Object.rds
Processing Gene: Stx3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Stx3_Combined_Plot_Object.rds
Skipping Gene: Gramd3 (Manually excluded).
Processing Gene: Stard9...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Stard9_Combined_Plot_Object.rds
Processing Gene: Pign...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Pign_Combined_Plot_Object.rds
Processing Gene: Il6st...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Il6st_Combined_Plot_Object.rds
Processing Gene: Dnajc5...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dnajc5_Combined_Plot_Object.rds
Processing Gene: Dcaf11...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dcaf11_Combined_Plot_Object.rds
Processing Gene: Srek1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Srek1_Combined_Plot_Object.rds
Processing Gene: Cage1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Cage1_Combined_Plot_Object.rds
Processing Gene: Unc13d...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Unc13d_Combined_Plot_Object.rds
Processing Gene: Mcm9...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Mcm9_Combined_Plot_Object.rds
Processing Gene: Rabep1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rabep1_Combined_Plot_Object.rds
Processing Gene: Fbxw11...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Fbxw11_Combined_Plot_Object.rds
Processing Gene: Eif4a2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Eif4a2_Combined_Plot_Object.rds
Processing Gene: Gmfg...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Gmfg_Combined_Plot_Object.rds
Processing Gene: Mettl15...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Mettl15_Combined_Plot_Object.rds
Processing Gene: Aurkaip1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Aurkaip1_Combined_Plot_Object.rds
Processing Gene: Dnajb5...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dnajb5_Combined_Plot_Object.rds
Processing Gene: Golga4...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Golga4_Combined_Plot_Object.rds
Processing Gene: Arap1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Arap1_Combined_Plot_Object.rds
Processing Gene: Myo7a...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Myo7a_Combined_Plot_Object.rds
Processing Gene: Rnasel...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rnasel_Combined_Plot_Object.rds
Processing Gene: Sulf2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sulf2_Combined_Plot_Object.rds
Processing Gene: Slc38a1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Slc38a1_Combined_Plot_Object.rds
Processing Gene: Oxr1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Oxr1_Combined_Plot_Object.rds
Processing Gene: Atxn7l1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Atxn7l1_Combined_Plot_Object.rds
Processing Gene: Eif2s3y...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Eif2s3y_Combined_Plot_Object.rds
Processing Gene: Dusp22...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Dusp22_Combined_Plot_Object.rds
Processing Gene: Gm12258...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Gm12258_Combined_Plot_Object.rds
Processing Gene: Zbtb38...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Zbtb38_Combined_Plot_Object.rds
Processing Gene: Sec31a...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sec31a_Combined_Plot_Object.rds
Processing Gene: Sigirr...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sigirr_Combined_Plot_Object.rds
Processing Gene: Rgs3...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Rgs3_Combined_Plot_Object.rds
Processing Gene: Yae1d1...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Yae1d1_Combined_Plot_Object.rds
Processing Gene: Pde11a...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Pde11a_Combined_Plot_Object.rds
Processing Gene: Sla...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Sla_Combined_Plot_Object.rds
Processing Gene: Gvin2...
   -> Saved plot object to: /group/soranzo/manuel.tardaguila/Bulk_RNA_seq/Santos/Reanalysis_2025/EXP1/DTU_graphs//Gvin2_Combined_Plot_Object.rds
Processing Gene: Eed...